// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;


public final class DomainState extends com.pulumi.resources.ResourceArgs {

    public static final DomainState Empty = new DomainState();

    @Import(name="arch")
    private @Nullable Output<String> arch;

    public Optional<Output<String>> arch() {
        return Optional.ofNullable(this.arch);
    }

    @Import(name="autostart")
    private @Nullable Output<Boolean> autostart;

    public Optional<Output<Boolean>> autostart() {
        return Optional.ofNullable(this.autostart);
    }

    @Import(name="bootDevices")
    private @Nullable Output<List<DomainBootDeviceArgs>> bootDevices;

    public Optional<Output<List<DomainBootDeviceArgs>>> bootDevices() {
        return Optional.ofNullable(this.bootDevices);
    }

    @Import(name="cloudinit")
    private @Nullable Output<String> cloudinit;

    public Optional<Output<String>> cloudinit() {
        return Optional.ofNullable(this.cloudinit);
    }

    @Import(name="cmdlines")
    private @Nullable Output<List<Map<String,String>>> cmdlines;

    public Optional<Output<List<Map<String,String>>>> cmdlines() {
        return Optional.ofNullable(this.cmdlines);
    }

    @Import(name="consoles")
    private @Nullable Output<List<DomainConsoleArgs>> consoles;

    public Optional<Output<List<DomainConsoleArgs>>> consoles() {
        return Optional.ofNullable(this.consoles);
    }

    @Import(name="coreosIgnition")
    private @Nullable Output<String> coreosIgnition;

    public Optional<Output<String>> coreosIgnition() {
        return Optional.ofNullable(this.coreosIgnition);
    }

    @Import(name="cpu")
    private @Nullable Output<DomainCpuArgs> cpu;

    public Optional<Output<DomainCpuArgs>> cpu() {
        return Optional.ofNullable(this.cpu);
    }

    @Import(name="description")
    private @Nullable Output<String> description;

    public Optional<Output<String>> description() {
        return Optional.ofNullable(this.description);
    }

    @Import(name="disks")
    private @Nullable Output<List<DomainDiskArgs>> disks;

    public Optional<Output<List<DomainDiskArgs>>> disks() {
        return Optional.ofNullable(this.disks);
    }

    @Import(name="domainId")
    private @Nullable Output<String> domainId;

    public Optional<Output<String>> domainId() {
        return Optional.ofNullable(this.domainId);
    }

    @Import(name="emulator")
    private @Nullable Output<String> emulator;

    public Optional<Output<String>> emulator() {
        return Optional.ofNullable(this.emulator);
    }

    @Import(name="filesystems")
    private @Nullable Output<List<DomainFilesystemArgs>> filesystems;

    public Optional<Output<List<DomainFilesystemArgs>>> filesystems() {
        return Optional.ofNullable(this.filesystems);
    }

    @Import(name="firmware")
    private @Nullable Output<String> firmware;

    public Optional<Output<String>> firmware() {
        return Optional.ofNullable(this.firmware);
    }

    @Import(name="fwCfgName")
    private @Nullable Output<String> fwCfgName;

    public Optional<Output<String>> fwCfgName() {
        return Optional.ofNullable(this.fwCfgName);
    }

    @Import(name="graphics")
    private @Nullable Output<DomainGraphicsArgs> graphics;

    public Optional<Output<DomainGraphicsArgs>> graphics() {
        return Optional.ofNullable(this.graphics);
    }

    @Import(name="initrd")
    private @Nullable Output<String> initrd;

    public Optional<Output<String>> initrd() {
        return Optional.ofNullable(this.initrd);
    }

    @Import(name="kernel")
    private @Nullable Output<String> kernel;

    public Optional<Output<String>> kernel() {
        return Optional.ofNullable(this.kernel);
    }

    @Import(name="machine")
    private @Nullable Output<String> machine;

    public Optional<Output<String>> machine() {
        return Optional.ofNullable(this.machine);
    }

    @Import(name="memory")
    private @Nullable Output<Double> memory;

    public Optional<Output<Double>> memory() {
        return Optional.ofNullable(this.memory);
    }

    @Import(name="metadata")
    private @Nullable Output<String> metadata;

    public Optional<Output<String>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="networkInterfaces")
    private @Nullable Output<List<DomainNetworkInterfaceArgs>> networkInterfaces;

    public Optional<Output<List<DomainNetworkInterfaceArgs>>> networkInterfaces() {
        return Optional.ofNullable(this.networkInterfaces);
    }

    @Import(name="nvram")
    private @Nullable Output<DomainNvramArgs> nvram;

    public Optional<Output<DomainNvramArgs>> nvram() {
        return Optional.ofNullable(this.nvram);
    }

    @Import(name="qemuAgent")
    private @Nullable Output<Boolean> qemuAgent;

    public Optional<Output<Boolean>> qemuAgent() {
        return Optional.ofNullable(this.qemuAgent);
    }

    @Import(name="running")
    private @Nullable Output<Boolean> running;

    public Optional<Output<Boolean>> running() {
        return Optional.ofNullable(this.running);
    }

    @Import(name="timeouts")
    private @Nullable Output<DomainTimeoutsArgs> timeouts;

    public Optional<Output<DomainTimeoutsArgs>> timeouts() {
        return Optional.ofNullable(this.timeouts);
    }

    @Import(name="tpm")
    private @Nullable Output<DomainTpmArgs> tpm;

    public Optional<Output<DomainTpmArgs>> tpm() {
        return Optional.ofNullable(this.tpm);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    @Import(name="vcpu")
    private @Nullable Output<Double> vcpu;

    public Optional<Output<Double>> vcpu() {
        return Optional.ofNullable(this.vcpu);
    }

    @Import(name="video")
    private @Nullable Output<DomainVideoArgs> video;

    public Optional<Output<DomainVideoArgs>> video() {
        return Optional.ofNullable(this.video);
    }

    @Import(name="xml")
    private @Nullable Output<DomainXmlArgs> xml;

    public Optional<Output<DomainXmlArgs>> xml() {
        return Optional.ofNullable(this.xml);
    }

    private DomainState() {}

    private DomainState(DomainState $) {
        this.arch = $.arch;
        this.autostart = $.autostart;
        this.bootDevices = $.bootDevices;
        this.cloudinit = $.cloudinit;
        this.cmdlines = $.cmdlines;
        this.consoles = $.consoles;
        this.coreosIgnition = $.coreosIgnition;
        this.cpu = $.cpu;
        this.description = $.description;
        this.disks = $.disks;
        this.domainId = $.domainId;
        this.emulator = $.emulator;
        this.filesystems = $.filesystems;
        this.firmware = $.firmware;
        this.fwCfgName = $.fwCfgName;
        this.graphics = $.graphics;
        this.initrd = $.initrd;
        this.kernel = $.kernel;
        this.machine = $.machine;
        this.memory = $.memory;
        this.metadata = $.metadata;
        this.name = $.name;
        this.networkInterfaces = $.networkInterfaces;
        this.nvram = $.nvram;
        this.qemuAgent = $.qemuAgent;
        this.running = $.running;
        this.timeouts = $.timeouts;
        this.tpm = $.tpm;
        this.type = $.type;
        this.vcpu = $.vcpu;
        this.video = $.video;
        this.xml = $.xml;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainState $;

        public Builder() {
            $ = new DomainState();
        }

        public Builder(DomainState defaults) {
            $ = new DomainState(Objects.requireNonNull(defaults));
        }

        public Builder arch(@Nullable Output<String> arch) {
            $.arch = arch;
            return this;
        }

        public Builder arch(String arch) {
            return arch(Output.of(arch));
        }

        public Builder autostart(@Nullable Output<Boolean> autostart) {
            $.autostart = autostart;
            return this;
        }

        public Builder autostart(Boolean autostart) {
            return autostart(Output.of(autostart));
        }

        public Builder bootDevices(@Nullable Output<List<DomainBootDeviceArgs>> bootDevices) {
            $.bootDevices = bootDevices;
            return this;
        }

        public Builder bootDevices(List<DomainBootDeviceArgs> bootDevices) {
            return bootDevices(Output.of(bootDevices));
        }

        public Builder bootDevices(DomainBootDeviceArgs... bootDevices) {
            return bootDevices(List.of(bootDevices));
        }

        public Builder cloudinit(@Nullable Output<String> cloudinit) {
            $.cloudinit = cloudinit;
            return this;
        }

        public Builder cloudinit(String cloudinit) {
            return cloudinit(Output.of(cloudinit));
        }

        public Builder cmdlines(@Nullable Output<List<Map<String,String>>> cmdlines) {
            $.cmdlines = cmdlines;
            return this;
        }

        public Builder cmdlines(List<Map<String,String>> cmdlines) {
            return cmdlines(Output.of(cmdlines));
        }

        public Builder cmdlines(@SuppressWarnings("unchecked") Map<String,String>... cmdlines) {
            return cmdlines(List.of(cmdlines));
        }

        public Builder consoles(@Nullable Output<List<DomainConsoleArgs>> consoles) {
            $.consoles = consoles;
            return this;
        }

        public Builder consoles(List<DomainConsoleArgs> consoles) {
            return consoles(Output.of(consoles));
        }

        public Builder consoles(DomainConsoleArgs... consoles) {
            return consoles(List.of(consoles));
        }

        public Builder coreosIgnition(@Nullable Output<String> coreosIgnition) {
            $.coreosIgnition = coreosIgnition;
            return this;
        }

        public Builder coreosIgnition(String coreosIgnition) {
            return coreosIgnition(Output.of(coreosIgnition));
        }

        public Builder cpu(@Nullable Output<DomainCpuArgs> cpu) {
            $.cpu = cpu;
            return this;
        }

        public Builder cpu(DomainCpuArgs cpu) {
            return cpu(Output.of(cpu));
        }

        public Builder description(@Nullable Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder disks(@Nullable Output<List<DomainDiskArgs>> disks) {
            $.disks = disks;
            return this;
        }

        public Builder disks(List<DomainDiskArgs> disks) {
            return disks(Output.of(disks));
        }

        public Builder disks(DomainDiskArgs... disks) {
            return disks(List.of(disks));
        }

        public Builder domainId(@Nullable Output<String> domainId) {
            $.domainId = domainId;
            return this;
        }

        public Builder domainId(String domainId) {
            return domainId(Output.of(domainId));
        }

        public Builder emulator(@Nullable Output<String> emulator) {
            $.emulator = emulator;
            return this;
        }

        public Builder emulator(String emulator) {
            return emulator(Output.of(emulator));
        }

        public Builder filesystems(@Nullable Output<List<DomainFilesystemArgs>> filesystems) {
            $.filesystems = filesystems;
            return this;
        }

        public Builder filesystems(List<DomainFilesystemArgs> filesystems) {
            return filesystems(Output.of(filesystems));
        }

        public Builder filesystems(DomainFilesystemArgs... filesystems) {
            return filesystems(List.of(filesystems));
        }

        public Builder firmware(@Nullable Output<String> firmware) {
            $.firmware = firmware;
            return this;
        }

        public Builder firmware(String firmware) {
            return firmware(Output.of(firmware));
        }

        public Builder fwCfgName(@Nullable Output<String> fwCfgName) {
            $.fwCfgName = fwCfgName;
            return this;
        }

        public Builder fwCfgName(String fwCfgName) {
            return fwCfgName(Output.of(fwCfgName));
        }

        public Builder graphics(@Nullable Output<DomainGraphicsArgs> graphics) {
            $.graphics = graphics;
            return this;
        }

        public Builder graphics(DomainGraphicsArgs graphics) {
            return graphics(Output.of(graphics));
        }

        public Builder initrd(@Nullable Output<String> initrd) {
            $.initrd = initrd;
            return this;
        }

        public Builder initrd(String initrd) {
            return initrd(Output.of(initrd));
        }

        public Builder kernel(@Nullable Output<String> kernel) {
            $.kernel = kernel;
            return this;
        }

        public Builder kernel(String kernel) {
            return kernel(Output.of(kernel));
        }

        public Builder machine(@Nullable Output<String> machine) {
            $.machine = machine;
            return this;
        }

        public Builder machine(String machine) {
            return machine(Output.of(machine));
        }

        public Builder memory(@Nullable Output<Double> memory) {
            $.memory = memory;
            return this;
        }

        public Builder memory(Double memory) {
            return memory(Output.of(memory));
        }

        public Builder metadata(@Nullable Output<String> metadata) {
            $.metadata = metadata;
            return this;
        }

        public Builder metadata(String metadata) {
            return metadata(Output.of(metadata));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder networkInterfaces(@Nullable Output<List<DomainNetworkInterfaceArgs>> networkInterfaces) {
            $.networkInterfaces = networkInterfaces;
            return this;
        }

        public Builder networkInterfaces(List<DomainNetworkInterfaceArgs> networkInterfaces) {
            return networkInterfaces(Output.of(networkInterfaces));
        }

        public Builder networkInterfaces(DomainNetworkInterfaceArgs... networkInterfaces) {
            return networkInterfaces(List.of(networkInterfaces));
        }

        public Builder nvram(@Nullable Output<DomainNvramArgs> nvram) {
            $.nvram = nvram;
            return this;
        }

        public Builder nvram(DomainNvramArgs nvram) {
            return nvram(Output.of(nvram));
        }

        public Builder qemuAgent(@Nullable Output<Boolean> qemuAgent) {
            $.qemuAgent = qemuAgent;
            return this;
        }

        public Builder qemuAgent(Boolean qemuAgent) {
            return qemuAgent(Output.of(qemuAgent));
        }

        public Builder running(@Nullable Output<Boolean> running) {
            $.running = running;
            return this;
        }

        public Builder running(Boolean running) {
            return running(Output.of(running));
        }

        public Builder timeouts(@Nullable Output<DomainTimeoutsArgs> timeouts) {
            $.timeouts = timeouts;
            return this;
        }

        public Builder timeouts(DomainTimeoutsArgs timeouts) {
            return timeouts(Output.of(timeouts));
        }

        public Builder tpm(@Nullable Output<DomainTpmArgs> tpm) {
            $.tpm = tpm;
            return this;
        }

        public Builder tpm(DomainTpmArgs tpm) {
            return tpm(Output.of(tpm));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public Builder vcpu(@Nullable Output<Double> vcpu) {
            $.vcpu = vcpu;
            return this;
        }

        public Builder vcpu(Double vcpu) {
            return vcpu(Output.of(vcpu));
        }

        public Builder video(@Nullable Output<DomainVideoArgs> video) {
            $.video = video;
            return this;
        }

        public Builder video(DomainVideoArgs video) {
            return video(Output.of(video));
        }

        public Builder xml(@Nullable Output<DomainXmlArgs> xml) {
            $.xml = xml;
            return this;
        }

        public Builder xml(DomainXmlArgs xml) {
            return xml(Output.of(xml));
        }

        public DomainState build() {
            return $;
        }
    }

}
