// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainDiskArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainDiskArgs Empty = new DomainDiskArgs();

    @Import(name="blockDevice")
    private @Nullable Output<String> blockDevice;

    public Optional<Output<String>> blockDevice() {
        return Optional.ofNullable(this.blockDevice);
    }

    @Import(name="file")
    private @Nullable Output<String> file;

    public Optional<Output<String>> file() {
        return Optional.ofNullable(this.file);
    }

    @Import(name="scsi")
    private @Nullable Output<Boolean> scsi;

    public Optional<Output<Boolean>> scsi() {
        return Optional.ofNullable(this.scsi);
    }

    @Import(name="url")
    private @Nullable Output<String> url;

    public Optional<Output<String>> url() {
        return Optional.ofNullable(this.url);
    }

    @Import(name="volumeId")
    private @Nullable Output<String> volumeId;

    public Optional<Output<String>> volumeId() {
        return Optional.ofNullable(this.volumeId);
    }

    @Import(name="wwn")
    private @Nullable Output<String> wwn;

    public Optional<Output<String>> wwn() {
        return Optional.ofNullable(this.wwn);
    }

    private DomainDiskArgs() {}

    private DomainDiskArgs(DomainDiskArgs $) {
        this.blockDevice = $.blockDevice;
        this.file = $.file;
        this.scsi = $.scsi;
        this.url = $.url;
        this.volumeId = $.volumeId;
        this.wwn = $.wwn;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainDiskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainDiskArgs $;

        public Builder() {
            $ = new DomainDiskArgs();
        }

        public Builder(DomainDiskArgs defaults) {
            $ = new DomainDiskArgs(Objects.requireNonNull(defaults));
        }

        public Builder blockDevice(@Nullable Output<String> blockDevice) {
            $.blockDevice = blockDevice;
            return this;
        }

        public Builder blockDevice(String blockDevice) {
            return blockDevice(Output.of(blockDevice));
        }

        public Builder file(@Nullable Output<String> file) {
            $.file = file;
            return this;
        }

        public Builder file(String file) {
            return file(Output.of(file));
        }

        public Builder scsi(@Nullable Output<Boolean> scsi) {
            $.scsi = scsi;
            return this;
        }

        public Builder scsi(Boolean scsi) {
            return scsi(Output.of(scsi));
        }

        public Builder url(@Nullable Output<String> url) {
            $.url = url;
            return this;
        }

        public Builder url(String url) {
            return url(Output.of(url));
        }

        public Builder volumeId(@Nullable Output<String> volumeId) {
            $.volumeId = volumeId;
            return this;
        }

        public Builder volumeId(String volumeId) {
            return volumeId(Output.of(volumeId));
        }

        public Builder wwn(@Nullable Output<String> wwn) {
            $.wwn = wwn;
            return this;
        }

        public Builder wwn(String wwn) {
            return wwn(Output.of(wwn));
        }

        public DomainDiskArgs build() {
            return $;
        }
    }

}
