// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainTpmArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainTpmArgs Empty = new DomainTpmArgs();

    @Import(name="backendDevicePath")
    private @Nullable Output<String> backendDevicePath;

    public Optional<Output<String>> backendDevicePath() {
        return Optional.ofNullable(this.backendDevicePath);
    }

    @Import(name="backendEncryptionSecret")
    private @Nullable Output<String> backendEncryptionSecret;

    public Optional<Output<String>> backendEncryptionSecret() {
        return Optional.ofNullable(this.backendEncryptionSecret);
    }

    @Import(name="backendPersistentState")
    private @Nullable Output<Boolean> backendPersistentState;

    public Optional<Output<Boolean>> backendPersistentState() {
        return Optional.ofNullable(this.backendPersistentState);
    }

    @Import(name="backendType")
    private @Nullable Output<String> backendType;

    public Optional<Output<String>> backendType() {
        return Optional.ofNullable(this.backendType);
    }

    @Import(name="backendVersion")
    private @Nullable Output<String> backendVersion;

    public Optional<Output<String>> backendVersion() {
        return Optional.ofNullable(this.backendVersion);
    }

    @Import(name="model")
    private @Nullable Output<String> model;

    public Optional<Output<String>> model() {
        return Optional.ofNullable(this.model);
    }

    private DomainTpmArgs() {}

    private DomainTpmArgs(DomainTpmArgs $) {
        this.backendDevicePath = $.backendDevicePath;
        this.backendEncryptionSecret = $.backendEncryptionSecret;
        this.backendPersistentState = $.backendPersistentState;
        this.backendType = $.backendType;
        this.backendVersion = $.backendVersion;
        this.model = $.model;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainTpmArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainTpmArgs $;

        public Builder() {
            $ = new DomainTpmArgs();
        }

        public Builder(DomainTpmArgs defaults) {
            $ = new DomainTpmArgs(Objects.requireNonNull(defaults));
        }

        public Builder backendDevicePath(@Nullable Output<String> backendDevicePath) {
            $.backendDevicePath = backendDevicePath;
            return this;
        }

        public Builder backendDevicePath(String backendDevicePath) {
            return backendDevicePath(Output.of(backendDevicePath));
        }

        public Builder backendEncryptionSecret(@Nullable Output<String> backendEncryptionSecret) {
            $.backendEncryptionSecret = backendEncryptionSecret;
            return this;
        }

        public Builder backendEncryptionSecret(String backendEncryptionSecret) {
            return backendEncryptionSecret(Output.of(backendEncryptionSecret));
        }

        public Builder backendPersistentState(@Nullable Output<Boolean> backendPersistentState) {
            $.backendPersistentState = backendPersistentState;
            return this;
        }

        public Builder backendPersistentState(Boolean backendPersistentState) {
            return backendPersistentState(Output.of(backendPersistentState));
        }

        public Builder backendType(@Nullable Output<String> backendType) {
            $.backendType = backendType;
            return this;
        }

        public Builder backendType(String backendType) {
            return backendType(Output.of(backendType));
        }

        public Builder backendVersion(@Nullable Output<String> backendVersion) {
            $.backendVersion = backendVersion;
            return this;
        }

        public Builder backendVersion(String backendVersion) {
            return backendVersion(Output.of(backendVersion));
        }

        public Builder model(@Nullable Output<String> model) {
            $.model = model;
            return this;
        }

        public Builder model(String model) {
            return model(Output.of(model));
        }

        public DomainTpmArgs build() {
            return $;
        }
    }

}
