// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainGraphicsArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainGraphicsArgs Empty = new DomainGraphicsArgs();

    @Import(name="autoport")
    private @Nullable Output<Boolean> autoport;

    public Optional<Output<Boolean>> autoport() {
        return Optional.ofNullable(this.autoport);
    }

    @Import(name="listenAddress")
    private @Nullable Output<String> listenAddress;

    public Optional<Output<String>> listenAddress() {
        return Optional.ofNullable(this.listenAddress);
    }

    @Import(name="listenType")
    private @Nullable Output<String> listenType;

    public Optional<Output<String>> listenType() {
        return Optional.ofNullable(this.listenType);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    @Import(name="websocket")
    private @Nullable Output<Double> websocket;

    public Optional<Output<Double>> websocket() {
        return Optional.ofNullable(this.websocket);
    }

    private DomainGraphicsArgs() {}

    private DomainGraphicsArgs(DomainGraphicsArgs $) {
        this.autoport = $.autoport;
        this.listenAddress = $.listenAddress;
        this.listenType = $.listenType;
        this.type = $.type;
        this.websocket = $.websocket;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainGraphicsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainGraphicsArgs $;

        public Builder() {
            $ = new DomainGraphicsArgs();
        }

        public Builder(DomainGraphicsArgs defaults) {
            $ = new DomainGraphicsArgs(Objects.requireNonNull(defaults));
        }

        public Builder autoport(@Nullable Output<Boolean> autoport) {
            $.autoport = autoport;
            return this;
        }

        public Builder autoport(Boolean autoport) {
            return autoport(Output.of(autoport));
        }

        public Builder listenAddress(@Nullable Output<String> listenAddress) {
            $.listenAddress = listenAddress;
            return this;
        }

        public Builder listenAddress(String listenAddress) {
            return listenAddress(Output.of(listenAddress));
        }

        public Builder listenType(@Nullable Output<String> listenType) {
            $.listenType = listenType;
            return this;
        }

        public Builder listenType(String listenType) {
            return listenType(Output.of(listenType));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public Builder websocket(@Nullable Output<Double> websocket) {
            $.websocket = websocket;
            return this;
        }

        public Builder websocket(Double websocket) {
            return websocket(Output.of(websocket));
        }

        public DomainGraphicsArgs build() {
            return $;
        }
    }

}
