// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainConsoleArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainConsoleArgs Empty = new DomainConsoleArgs();

    @Import(name="sourceHost")
    private @Nullable Output<String> sourceHost;

    public Optional<Output<String>> sourceHost() {
        return Optional.ofNullable(this.sourceHost);
    }

    @Import(name="sourcePath")
    private @Nullable Output<String> sourcePath;

    public Optional<Output<String>> sourcePath() {
        return Optional.ofNullable(this.sourcePath);
    }

    @Import(name="sourceService")
    private @Nullable Output<String> sourceService;

    public Optional<Output<String>> sourceService() {
        return Optional.ofNullable(this.sourceService);
    }

    @Import(name="targetPort", required=true)
    private Output<String> targetPort;

    public Output<String> targetPort() {
        return this.targetPort;
    }

    @Import(name="targetType")
    private @Nullable Output<String> targetType;

    public Optional<Output<String>> targetType() {
        return Optional.ofNullable(this.targetType);
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    private DomainConsoleArgs() {}

    private DomainConsoleArgs(DomainConsoleArgs $) {
        this.sourceHost = $.sourceHost;
        this.sourcePath = $.sourcePath;
        this.sourceService = $.sourceService;
        this.targetPort = $.targetPort;
        this.targetType = $.targetType;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainConsoleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainConsoleArgs $;

        public Builder() {
            $ = new DomainConsoleArgs();
        }

        public Builder(DomainConsoleArgs defaults) {
            $ = new DomainConsoleArgs(Objects.requireNonNull(defaults));
        }

        public Builder sourceHost(@Nullable Output<String> sourceHost) {
            $.sourceHost = sourceHost;
            return this;
        }

        public Builder sourceHost(String sourceHost) {
            return sourceHost(Output.of(sourceHost));
        }

        public Builder sourcePath(@Nullable Output<String> sourcePath) {
            $.sourcePath = sourcePath;
            return this;
        }

        public Builder sourcePath(String sourcePath) {
            return sourcePath(Output.of(sourcePath));
        }

        public Builder sourceService(@Nullable Output<String> sourceService) {
            $.sourceService = sourceService;
            return this;
        }

        public Builder sourceService(String sourceService) {
            return sourceService(Output.of(sourceService));
        }

        public Builder targetPort(Output<String> targetPort) {
            $.targetPort = targetPort;
            return this;
        }

        public Builder targetPort(String targetPort) {
            return targetPort(Output.of(targetPort));
        }

        public Builder targetType(@Nullable Output<String> targetType) {
            $.targetType = targetType;
            return this;
        }

        public Builder targetType(String targetType) {
            return targetType(Output.of(targetType));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public DomainConsoleArgs build() {
            if ($.targetPort == null) {
                throw new MissingRequiredPropertyException("DomainConsoleArgs", "targetPort");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("DomainConsoleArgs", "type");
            }
            return $;
        }
    }

}
