// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import java.util.Objects;
import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;


public final class GetNodeDeviceInfoArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeDeviceInfoArgs Empty = new GetNodeDeviceInfoArgs();

    @Import(name="capability")
    private @Nullable Output<GetNodeDeviceInfoCapabilityArgs> capability;

    public Optional<Output<GetNodeDeviceInfoCapabilityArgs>> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    private GetNodeDeviceInfoArgs() {}

    private GetNodeDeviceInfoArgs(GetNodeDeviceInfoArgs $) {
        this.capability = $.capability;
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDeviceInfoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDeviceInfoArgs $;

        public Builder() {
            $ = new GetNodeDeviceInfoArgs();
        }

        public Builder(GetNodeDeviceInfoArgs defaults) {
            $ = new GetNodeDeviceInfoArgs(Objects.requireNonNull(defaults));
        }

        public Builder capability(@Nullable Output<GetNodeDeviceInfoCapabilityArgs> capability) {
            $.capability = capability;
            return this;
        }

        public Builder capability(GetNodeDeviceInfoCapabilityArgs capability) {
            return capability(Output.of(capability));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetNodeDeviceInfoArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoArgs", "name");
            }
            return $;
        }
    }

}
