// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import java.util.Objects;
import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;


public final class GetNodeDeviceInfoPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeDeviceInfoPlainArgs Empty = new GetNodeDeviceInfoPlainArgs();

    @Import(name="capability")
    private @Nullable GetNodeDeviceInfoCapability capability;

    public Optional<GetNodeDeviceInfoCapability> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    @Import(name="name", required=true)
    private String name;

    public String name() {
        return this.name;
    }

    private GetNodeDeviceInfoPlainArgs() {}

    private GetNodeDeviceInfoPlainArgs(GetNodeDeviceInfoPlainArgs $) {
        this.capability = $.capability;
        this.id = $.id;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDeviceInfoPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDeviceInfoPlainArgs $;

        public Builder() {
            $ = new GetNodeDeviceInfoPlainArgs();
        }

        public Builder(GetNodeDeviceInfoPlainArgs defaults) {
            $ = new GetNodeDeviceInfoPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder capability(@Nullable GetNodeDeviceInfoCapability capability) {
            $.capability = capability;
            return this;
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public Builder name(String name) {
            $.name = name;
            return this;
        }

        public GetNodeDeviceInfoPlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoPlainArgs", "name");
            }
            return $;
        }
    }

}
