// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeDevicesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeDevicesPlainArgs Empty = new GetNodeDevicesPlainArgs();

    @Import(name="capability")
    private @Nullable String capability;

    public Optional<String> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    private GetNodeDevicesPlainArgs() {}

    private GetNodeDevicesPlainArgs(GetNodeDevicesPlainArgs $) {
        this.capability = $.capability;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDevicesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDevicesPlainArgs $;

        public Builder() {
            $ = new GetNodeDevicesPlainArgs();
        }

        public Builder(GetNodeDevicesPlainArgs defaults) {
            $ = new GetNodeDevicesPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder capability(@Nullable String capability) {
            $.capability = capability;
            return this;
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public GetNodeDevicesPlainArgs build() {
            return $;
        }
    }

}
