// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IgnitionState extends com.pulumi.resources.ResourceArgs {

    public static final IgnitionState Empty = new IgnitionState();

    @Import(name="content")
    private @Nullable Output<String> content;

    public Optional<Output<String>> content() {
        return Optional.ofNullable(this.content);
    }

    @Import(name="ignitionId")
    private @Nullable Output<String> ignitionId;

    public Optional<Output<String>> ignitionId() {
        return Optional.ofNullable(this.ignitionId);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="pool")
    private @Nullable Output<String> pool;

    public Optional<Output<String>> pool() {
        return Optional.ofNullable(this.pool);
    }

    private IgnitionState() {}

    private IgnitionState(IgnitionState $) {
        this.content = $.content;
        this.ignitionId = $.ignitionId;
        this.name = $.name;
        this.pool = $.pool;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IgnitionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IgnitionState $;

        public Builder() {
            $ = new IgnitionState();
        }

        public Builder(IgnitionState defaults) {
            $ = new IgnitionState(Objects.requireNonNull(defaults));
        }

        public Builder content(@Nullable Output<String> content) {
            $.content = content;
            return this;
        }

        public Builder content(String content) {
            return content(Output.of(content));
        }

        public Builder ignitionId(@Nullable Output<String> ignitionId) {
            $.ignitionId = ignitionId;
            return this;
        }

        public Builder ignitionId(String ignitionId) {
            return ignitionId(Output.of(ignitionId));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder pool(@Nullable Output<String> pool) {
            $.pool = pool;
            return this;
        }

        public Builder pool(String pool) {
            return pool(Output.of(pool));
        }

        public IgnitionState build() {
            return $;
        }
    }

}
