// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;


public final class NetworkDnsArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkDnsArgs Empty = new NetworkDnsArgs();

    @Import(name="enabled")
    private @Nullable Output<Boolean> enabled;

    public Optional<Output<Boolean>> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    @Import(name="forwarders")
    private @Nullable Output<List<NetworkDnsForwarderArgs>> forwarders;

    public Optional<Output<List<NetworkDnsForwarderArgs>>> forwarders() {
        return Optional.ofNullable(this.forwarders);
    }

    @Import(name="hosts")
    private @Nullable Output<List<NetworkDnsHostArgs>> hosts;

    public Optional<Output<List<NetworkDnsHostArgs>>> hosts() {
        return Optional.ofNullable(this.hosts);
    }

    @Import(name="localOnly")
    private @Nullable Output<Boolean> localOnly;

    public Optional<Output<Boolean>> localOnly() {
        return Optional.ofNullable(this.localOnly);
    }

    @Import(name="srvs")
    private @Nullable Output<List<NetworkDnsSrvArgs>> srvs;

    public Optional<Output<List<NetworkDnsSrvArgs>>> srvs() {
        return Optional.ofNullable(this.srvs);
    }

    private NetworkDnsArgs() {}

    private NetworkDnsArgs(NetworkDnsArgs $) {
        this.enabled = $.enabled;
        this.forwarders = $.forwarders;
        this.hosts = $.hosts;
        this.localOnly = $.localOnly;
        this.srvs = $.srvs;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkDnsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkDnsArgs $;

        public Builder() {
            $ = new NetworkDnsArgs();
        }

        public Builder(NetworkDnsArgs defaults) {
            $ = new NetworkDnsArgs(Objects.requireNonNull(defaults));
        }

        public Builder enabled(@Nullable Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        public Builder forwarders(@Nullable Output<List<NetworkDnsForwarderArgs>> forwarders) {
            $.forwarders = forwarders;
            return this;
        }

        public Builder forwarders(List<NetworkDnsForwarderArgs> forwarders) {
            return forwarders(Output.of(forwarders));
        }

        public Builder forwarders(NetworkDnsForwarderArgs... forwarders) {
            return forwarders(List.of(forwarders));
        }

        public Builder hosts(@Nullable Output<List<NetworkDnsHostArgs>> hosts) {
            $.hosts = hosts;
            return this;
        }

        public Builder hosts(List<NetworkDnsHostArgs> hosts) {
            return hosts(Output.of(hosts));
        }

        public Builder hosts(NetworkDnsHostArgs... hosts) {
            return hosts(List.of(hosts));
        }

        public Builder localOnly(@Nullable Output<Boolean> localOnly) {
            $.localOnly = localOnly;
            return this;
        }

        public Builder localOnly(Boolean localOnly) {
            return localOnly(Output.of(localOnly));
        }

        public Builder srvs(@Nullable Output<List<NetworkDnsSrvArgs>> srvs) {
            $.srvs = srvs;
            return this;
        }

        public Builder srvs(List<NetworkDnsSrvArgs> srvs) {
            return srvs(Output.of(srvs));
        }

        public Builder srvs(NetworkDnsSrvArgs... srvs) {
            return srvs(List.of(srvs));
        }

        public NetworkDnsArgs build() {
            return $;
        }
    }

}
