// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainGraphics {
    private @Nullable Boolean autoport;
    private @Nullable String listenAddress;
    private @Nullable String listenType;
    private @Nullable String type;
    private @Nullable Double websocket;

    private DomainGraphics() {}
    public Optional<Boolean> autoport() {
        return Optional.ofNullable(this.autoport);
    }
    public Optional<String> listenAddress() {
        return Optional.ofNullable(this.listenAddress);
    }
    public Optional<String> listenType() {
        return Optional.ofNullable(this.listenType);
    }
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    public Optional<Double> websocket() {
        return Optional.ofNullable(this.websocket);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainGraphics defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean autoport;
        private @Nullable String listenAddress;
        private @Nullable String listenType;
        private @Nullable String type;
        private @Nullable Double websocket;
        public Builder() {}
        public Builder(DomainGraphics defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.autoport = defaults.autoport;
    	      this.listenAddress = defaults.listenAddress;
    	      this.listenType = defaults.listenType;
    	      this.type = defaults.type;
    	      this.websocket = defaults.websocket;
        }

        @CustomType.Setter
        public Builder autoport(@Nullable Boolean autoport) {

            this.autoport = autoport;
            return this;
        }
        @CustomType.Setter
        public Builder listenAddress(@Nullable String listenAddress) {

            this.listenAddress = listenAddress;
            return this;
        }
        @CustomType.Setter
        public Builder listenType(@Nullable String listenType) {

            this.listenType = listenType;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder websocket(@Nullable Double websocket) {

            this.websocket = websocket;
            return this;
        }
        public DomainGraphics build() {
            final var _resultValue = new DomainGraphics();
            _resultValue.autoport = autoport;
            _resultValue.listenAddress = listenAddress;
            _resultValue.listenType = listenType;
            _resultValue.type = type;
            _resultValue.websocket = websocket;
            return _resultValue;
        }
    }
}
