// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainTimeouts {
    private @Nullable String create;

    private DomainTimeouts() {}
    public Optional<String> create() {
        return Optional.ofNullable(this.create);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainTimeouts defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String create;
        public Builder() {}
        public Builder(DomainTimeouts defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.create = defaults.create;
        }

        @CustomType.Setter
        public Builder create(@Nullable String create) {

            this.create = create;
            return this;
        }
        public DomainTimeouts build() {
            final var _resultValue = new DomainTimeouts();
            _resultValue.create = create;
            return _resultValue;
        }
    }
}
