// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainConsole {
    private @Nullable String sourceHost;
    private @Nullable String sourcePath;
    private @Nullable String sourceService;
    private String targetPort;
    private @Nullable String targetType;
    private String type;

    private DomainConsole() {}
    public Optional<String> sourceHost() {
        return Optional.ofNullable(this.sourceHost);
    }
    public Optional<String> sourcePath() {
        return Optional.ofNullable(this.sourcePath);
    }
    public Optional<String> sourceService() {
        return Optional.ofNullable(this.sourceService);
    }
    public String targetPort() {
        return this.targetPort;
    }
    public Optional<String> targetType() {
        return Optional.ofNullable(this.targetType);
    }
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainConsole defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String sourceHost;
        private @Nullable String sourcePath;
        private @Nullable String sourceService;
        private String targetPort;
        private @Nullable String targetType;
        private String type;
        public Builder() {}
        public Builder(DomainConsole defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.sourceHost = defaults.sourceHost;
    	      this.sourcePath = defaults.sourcePath;
    	      this.sourceService = defaults.sourceService;
    	      this.targetPort = defaults.targetPort;
    	      this.targetType = defaults.targetType;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder sourceHost(@Nullable String sourceHost) {

            this.sourceHost = sourceHost;
            return this;
        }
        @CustomType.Setter
        public Builder sourcePath(@Nullable String sourcePath) {

            this.sourcePath = sourcePath;
            return this;
        }
        @CustomType.Setter
        public Builder sourceService(@Nullable String sourceService) {

            this.sourceService = sourceService;
            return this;
        }
        @CustomType.Setter
        public Builder targetPort(String targetPort) {
            if (targetPort == null) {
              throw new MissingRequiredPropertyException("DomainConsole", "targetPort");
            }
            this.targetPort = targetPort;
            return this;
        }
        @CustomType.Setter
        public Builder targetType(@Nullable String targetType) {

            this.targetType = targetType;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("DomainConsole", "type");
            }
            this.type = type;
            return this;
        }
        public DomainConsole build() {
            final var _resultValue = new DomainConsole();
            _resultValue.sourceHost = sourceHost;
            _resultValue.sourcePath = sourcePath;
            _resultValue.sourceService = sourceService;
            _resultValue.targetPort = targetPort;
            _resultValue.targetType = targetType;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
