// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class CloudinitDiskArgs extends com.pulumi.resources.ResourceArgs {

    public static final CloudinitDiskArgs Empty = new CloudinitDiskArgs();

    @Import(name="cloudinitDiskId")
    private @Nullable Output<String> cloudinitDiskId;

    public Optional<Output<String>> cloudinitDiskId() {
        return Optional.ofNullable(this.cloudinitDiskId);
    }

    @Import(name="metaData")
    private @Nullable Output<String> metaData;

    public Optional<Output<String>> metaData() {
        return Optional.ofNullable(this.metaData);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="networkConfig")
    private @Nullable Output<String> networkConfig;

    public Optional<Output<String>> networkConfig() {
        return Optional.ofNullable(this.networkConfig);
    }

    @Import(name="pool")
    private @Nullable Output<String> pool;

    public Optional<Output<String>> pool() {
        return Optional.ofNullable(this.pool);
    }

    @Import(name="userData")
    private @Nullable Output<String> userData;

    public Optional<Output<String>> userData() {
        return Optional.ofNullable(this.userData);
    }

    private CloudinitDiskArgs() {}

    private CloudinitDiskArgs(CloudinitDiskArgs $) {
        this.cloudinitDiskId = $.cloudinitDiskId;
        this.metaData = $.metaData;
        this.name = $.name;
        this.networkConfig = $.networkConfig;
        this.pool = $.pool;
        this.userData = $.userData;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CloudinitDiskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CloudinitDiskArgs $;

        public Builder() {
            $ = new CloudinitDiskArgs();
        }

        public Builder(CloudinitDiskArgs defaults) {
            $ = new CloudinitDiskArgs(Objects.requireNonNull(defaults));
        }

        public Builder cloudinitDiskId(@Nullable Output<String> cloudinitDiskId) {
            $.cloudinitDiskId = cloudinitDiskId;
            return this;
        }

        public Builder cloudinitDiskId(String cloudinitDiskId) {
            return cloudinitDiskId(Output.of(cloudinitDiskId));
        }

        public Builder metaData(@Nullable Output<String> metaData) {
            $.metaData = metaData;
            return this;
        }

        public Builder metaData(String metaData) {
            return metaData(Output.of(metaData));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder networkConfig(@Nullable Output<String> networkConfig) {
            $.networkConfig = networkConfig;
            return this;
        }

        public Builder networkConfig(String networkConfig) {
            return networkConfig(Output.of(networkConfig));
        }

        public Builder pool(@Nullable Output<String> pool) {
            $.pool = pool;
            return this;
        }

        public Builder pool(String pool) {
            return pool(Output.of(pool));
        }

        public Builder userData(@Nullable Output<String> userData) {
            $.userData = userData;
            return this;
        }

        public Builder userData(String userData) {
            return userData(Output.of(userData));
        }

        public CloudinitDiskArgs build() {
            return $;
        }
    }

}
