// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.internal.Codegen;

public final class Config {

    @SuppressWarnings("deprecation")
    private static final com.pulumi.Config config = com.pulumi.Config.of("libvirt");
/**
 * libvirt connection URI for operations. See https://libvirt.org/uri.html
 * 
 */
    public String uri() {
        return Codegen.stringProp("uri").config(config).require();
    }
}
