// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.libvirt.inputs.DomainState;
import com.pulumi.libvirt.outputs.DomainBootDevice;
import com.pulumi.libvirt.outputs.DomainConsole;
import com.pulumi.libvirt.outputs.DomainCpu;
import com.pulumi.libvirt.outputs.DomainDisk;
import com.pulumi.libvirt.outputs.DomainFilesystem;
import com.pulumi.libvirt.outputs.DomainGraphics;
import com.pulumi.libvirt.outputs.DomainNetworkInterface;
import com.pulumi.libvirt.outputs.DomainNvram;
import com.pulumi.libvirt.outputs.DomainTimeouts;
import com.pulumi.libvirt.outputs.DomainTpm;
import com.pulumi.libvirt.outputs.DomainVideo;
import com.pulumi.libvirt.outputs.DomainXml;

@ResourceType(type="libvirt:index/domain:Domain")
public class Domain extends com.pulumi.resources.CustomResource {
    @Export(name="arch", refs={String.class}, tree="[0]")
    private Output<String> arch;

    public Output<String> arch() {
        return this.arch;
    }
    @Export(name="autostart", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> autostart;

    public Output<Boolean> autostart() {
        return this.autostart;
    }
    @Export(name="bootDevices", refs={List.class,DomainBootDevice.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainBootDevice>> bootDevices;

    public Output<Optional<List<DomainBootDevice>>> bootDevices() {
        return Codegen.optional(this.bootDevices);
    }
    @Export(name="cloudinit", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cloudinit;

    public Output<Optional<String>> cloudinit() {
        return Codegen.optional(this.cloudinit);
    }
    @Export(name="cmdlines", refs={List.class,Map.class,String.class}, tree="[0,[1,2,2]]")
    private Output</* @Nullable */ List<Map<String,String>>> cmdlines;

    public Output<Optional<List<Map<String,String>>>> cmdlines() {
        return Codegen.optional(this.cmdlines);
    }
    @Export(name="consoles", refs={List.class,DomainConsole.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainConsole>> consoles;

    public Output<Optional<List<DomainConsole>>> consoles() {
        return Codegen.optional(this.consoles);
    }
    @Export(name="coreosIgnition", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> coreosIgnition;

    public Output<Optional<String>> coreosIgnition() {
        return Codegen.optional(this.coreosIgnition);
    }
    @Export(name="cpu", refs={DomainCpu.class}, tree="[0]")
    private Output</* @Nullable */ DomainCpu> cpu;

    public Output<Optional<DomainCpu>> cpu() {
        return Codegen.optional(this.cpu);
    }
    @Export(name="description", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> description;

    public Output<Optional<String>> description() {
        return Codegen.optional(this.description);
    }
    @Export(name="disks", refs={List.class,DomainDisk.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainDisk>> disks;

    public Output<Optional<List<DomainDisk>>> disks() {
        return Codegen.optional(this.disks);
    }
    @Export(name="domainId", refs={String.class}, tree="[0]")
    private Output<String> domainId;

    public Output<String> domainId() {
        return this.domainId;
    }
    @Export(name="emulator", refs={String.class}, tree="[0]")
    private Output<String> emulator;

    public Output<String> emulator() {
        return this.emulator;
    }
    @Export(name="filesystems", refs={List.class,DomainFilesystem.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainFilesystem>> filesystems;

    public Output<Optional<List<DomainFilesystem>>> filesystems() {
        return Codegen.optional(this.filesystems);
    }
    @Export(name="firmware", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> firmware;

    public Output<Optional<String>> firmware() {
        return Codegen.optional(this.firmware);
    }
    @Export(name="fwCfgName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> fwCfgName;

    public Output<Optional<String>> fwCfgName() {
        return Codegen.optional(this.fwCfgName);
    }
    @Export(name="graphics", refs={DomainGraphics.class}, tree="[0]")
    private Output</* @Nullable */ DomainGraphics> graphics;

    public Output<Optional<DomainGraphics>> graphics() {
        return Codegen.optional(this.graphics);
    }
    @Export(name="initrd", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> initrd;

    public Output<Optional<String>> initrd() {
        return Codegen.optional(this.initrd);
    }
    @Export(name="kernel", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> kernel;

    public Output<Optional<String>> kernel() {
        return Codegen.optional(this.kernel);
    }
    @Export(name="machine", refs={String.class}, tree="[0]")
    private Output<String> machine;

    public Output<String> machine() {
        return this.machine;
    }
    @Export(name="memory", refs={Double.class}, tree="[0]")
    private Output</* @Nullable */ Double> memory;

    public Output<Optional<Double>> memory() {
        return Codegen.optional(this.memory);
    }
    @Export(name="metadata", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> metadata;

    public Output<Optional<String>> metadata() {
        return Codegen.optional(this.metadata);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="networkInterfaces", refs={List.class,DomainNetworkInterface.class}, tree="[0,1]")
    private Output</* @Nullable */ List<DomainNetworkInterface>> networkInterfaces;

    public Output<Optional<List<DomainNetworkInterface>>> networkInterfaces() {
        return Codegen.optional(this.networkInterfaces);
    }
    @Export(name="nvram", refs={DomainNvram.class}, tree="[0]")
    private Output</* @Nullable */ DomainNvram> nvram;

    public Output<Optional<DomainNvram>> nvram() {
        return Codegen.optional(this.nvram);
    }
    @Export(name="qemuAgent", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> qemuAgent;

    public Output<Optional<Boolean>> qemuAgent() {
        return Codegen.optional(this.qemuAgent);
    }
    @Export(name="running", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> running;

    public Output<Optional<Boolean>> running() {
        return Codegen.optional(this.running);
    }
    @Export(name="timeouts", refs={DomainTimeouts.class}, tree="[0]")
    private Output</* @Nullable */ DomainTimeouts> timeouts;

    public Output<Optional<DomainTimeouts>> timeouts() {
        return Codegen.optional(this.timeouts);
    }
    @Export(name="tpm", refs={DomainTpm.class}, tree="[0]")
    private Output</* @Nullable */ DomainTpm> tpm;

    public Output<Optional<DomainTpm>> tpm() {
        return Codegen.optional(this.tpm);
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> type;

    public Output<Optional<String>> type() {
        return Codegen.optional(this.type);
    }
    @Export(name="vcpu", refs={Double.class}, tree="[0]")
    private Output</* @Nullable */ Double> vcpu;

    public Output<Optional<Double>> vcpu() {
        return Codegen.optional(this.vcpu);
    }
    @Export(name="video", refs={DomainVideo.class}, tree="[0]")
    private Output</* @Nullable */ DomainVideo> video;

    public Output<Optional<DomainVideo>> video() {
        return Codegen.optional(this.video);
    }
    @Export(name="xml", refs={DomainXml.class}, tree="[0]")
    private Output</* @Nullable */ DomainXml> xml;

    public Output<Optional<DomainXml>> xml() {
        return Codegen.optional(this.xml);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Domain(java.lang.String name) {
        this(name, DomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Domain(java.lang.String name, @Nullable DomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Domain(java.lang.String name, @Nullable DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/domain:Domain", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private Domain(java.lang.String name, Output<java.lang.String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/domain:Domain", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static DomainArgs makeArgs(@Nullable DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Domain get(java.lang.String name, Output<java.lang.String> id, @Nullable DomainState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Domain(name, id, state, options);
    }
}
