// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.libvirt.inputs.NetworkState;
import com.pulumi.libvirt.outputs.NetworkDhcp;
import com.pulumi.libvirt.outputs.NetworkDns;
import com.pulumi.libvirt.outputs.NetworkDnsmasqOptions;
import com.pulumi.libvirt.outputs.NetworkRoute;
import com.pulumi.libvirt.outputs.NetworkXml;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="libvirt:index/network:Network")
public class Network extends com.pulumi.resources.CustomResource {
    @Export(name="addresses", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> addresses;

    public Output<Optional<List<String>>> addresses() {
        return Codegen.optional(this.addresses);
    }
    @Export(name="autostart", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> autostart;

    public Output<Boolean> autostart() {
        return this.autostart;
    }
    @Export(name="bridge", refs={String.class}, tree="[0]")
    private Output<String> bridge;

    public Output<String> bridge() {
        return this.bridge;
    }
    @Export(name="dhcp", refs={NetworkDhcp.class}, tree="[0]")
    private Output</* @Nullable */ NetworkDhcp> dhcp;

    public Output<Optional<NetworkDhcp>> dhcp() {
        return Codegen.optional(this.dhcp);
    }
    @Export(name="dns", refs={NetworkDns.class}, tree="[0]")
    private Output</* @Nullable */ NetworkDns> dns;

    public Output<Optional<NetworkDns>> dns() {
        return Codegen.optional(this.dns);
    }
    @Export(name="dnsmasqOptions", refs={NetworkDnsmasqOptions.class}, tree="[0]")
    private Output</* @Nullable */ NetworkDnsmasqOptions> dnsmasqOptions;

    public Output<Optional<NetworkDnsmasqOptions>> dnsmasqOptions() {
        return Codegen.optional(this.dnsmasqOptions);
    }
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> domain;

    public Output<Optional<String>> domain() {
        return Codegen.optional(this.domain);
    }
    @Export(name="mode", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> mode;

    public Output<Optional<String>> mode() {
        return Codegen.optional(this.mode);
    }
    @Export(name="mtu", refs={Double.class}, tree="[0]")
    private Output</* @Nullable */ Double> mtu;

    public Output<Optional<Double>> mtu() {
        return Codegen.optional(this.mtu);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="networkId", refs={String.class}, tree="[0]")
    private Output<String> networkId;

    public Output<String> networkId() {
        return this.networkId;
    }
    @Export(name="routes", refs={List.class,NetworkRoute.class}, tree="[0,1]")
    private Output</* @Nullable */ List<NetworkRoute>> routes;

    public Output<Optional<List<NetworkRoute>>> routes() {
        return Codegen.optional(this.routes);
    }
    @Export(name="xml", refs={NetworkXml.class}, tree="[0]")
    private Output</* @Nullable */ NetworkXml> xml;

    public Output<Optional<NetworkXml>> xml() {
        return Codegen.optional(this.xml);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Network(java.lang.String name) {
        this(name, NetworkArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Network(java.lang.String name, @Nullable NetworkArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Network(java.lang.String name, @Nullable NetworkArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/network:Network", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private Network(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/network:Network", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static NetworkArgs makeArgs(@Nullable NetworkArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? NetworkArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Network get(java.lang.String name, Output<java.lang.String> id, @Nullable NetworkState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Network(name, id, state, options);
    }
}
