// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import java.util.Optional;

import javax.annotation.Nullable;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.libvirt.inputs.PoolState;
import com.pulumi.libvirt.outputs.PoolSource;
import com.pulumi.libvirt.outputs.PoolTarget;
import com.pulumi.libvirt.outputs.PoolXml;

@ResourceType(type="libvirt:index/pool:Pool")
public class Pool extends com.pulumi.resources.CustomResource {
    @Export(name="allocation", refs={Double.class}, tree="[0]")
    private Output<Double> allocation;

    public Output<Double> allocation() {
        return this.allocation;
    }
    @Export(name="available", refs={Double.class}, tree="[0]")
    private Output<Double> available;

    public Output<Double> available() {
        return this.available;
    }
    @Export(name="capacity", refs={Double.class}, tree="[0]")
    private Output<Double> capacity;

    public Output<Double> capacity() {
        return this.capacity;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    /**
     * @deprecated
     * Deprecated
     * 
     */
    @Deprecated /* Deprecated */
    @Export(name="path", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> path;

    public Output<Optional<String>> path() {
        return Codegen.optional(this.path);
    }
    @Export(name="poolId", refs={String.class}, tree="[0]")
    private Output<String> poolId;

    public Output<String> poolId() {
        return this.poolId;
    }
    @Export(name="source", refs={PoolSource.class}, tree="[0]")
    private Output</* @Nullable */ PoolSource> source;

    public Output<Optional<PoolSource>> source() {
        return Codegen.optional(this.source);
    }
    @Export(name="target", refs={PoolTarget.class}, tree="[0]")
    private Output</* @Nullable */ PoolTarget> target;

    public Output<Optional<PoolTarget>> target() {
        return Codegen.optional(this.target);
    }
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }
    @Export(name="xml", refs={PoolXml.class}, tree="[0]")
    private Output</* @Nullable */ PoolXml> xml;

    public Output<Optional<PoolXml>> xml() {
        return Codegen.optional(this.xml);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Pool(java.lang.String name) {
        this(name, PoolArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Pool(java.lang.String name, PoolArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Pool(java.lang.String name, PoolArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/pool:Pool", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private Pool(java.lang.String name, Output<java.lang.String> id, @Nullable PoolState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/pool:Pool", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static PoolArgs makeArgs(PoolArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? PoolArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Pool get(java.lang.String name, Output<java.lang.String> id, @Nullable PoolState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Pool(name, id, state, options);
    }
}
