// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * libvirt connection URI for operations. See https://libvirt.org/uri.html
     * 
     */
    @Import(name="uri", required=true)
    private Output<String> uri;

    /**
     * @return libvirt connection URI for operations. See https://libvirt.org/uri.html
     * 
     */
    public Output<String> uri() {
        return this.uri;
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.uri = $.uri;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param uri libvirt connection URI for operations. See https://libvirt.org/uri.html
         * 
         * @return builder
         * 
         */
        public Builder uri(Output<String> uri) {
            $.uri = uri;
            return this;
        }

        /**
         * @param uri libvirt connection URI for operations. See https://libvirt.org/uri.html
         * 
         * @return builder
         * 
         */
        public Builder uri(String uri) {
            return uri(Output.of(uri));
        }

        public ProviderArgs build() {
            if ($.uri == null) {
                throw new MissingRequiredPropertyException("ProviderArgs", "uri");
            }
            return $;
        }
    }

}
