#cloud-config

version: 2
hostname: router

users:
- name: ansible
  gecos: Ansible User
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  lock_passwd: false
  passwd: $1$MG0Le6DD$Qxxbq7fPZDxFko.FWO8AD.
  ssh_authorized_keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHvLLOfW6pZChoYquT20z4VaP9Lqo/0Uk5vZ22CUJ5BQ green1490@192.168.1.74