// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.libvirt.CloudinitDiskArgs;
import com.pulumi.libvirt.Utilities;
import com.pulumi.libvirt.inputs.CloudinitDiskState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="libvirt:index/cloudinitDisk:CloudinitDisk")
public class CloudinitDisk extends com.pulumi.resources.CustomResource {
    @Export(name="cloudinitDiskId", refs={String.class}, tree="[0]")
    private Output<String> cloudinitDiskId;

    public Output<String> cloudinitDiskId() {
        return this.cloudinitDiskId;
    }
    @Export(name="metaData", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> metaData;

    public Output<Optional<String>> metaData() {
        return Codegen.optional(this.metaData);
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="networkConfig", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> networkConfig;

    public Output<Optional<String>> networkConfig() {
        return Codegen.optional(this.networkConfig);
    }
    @Export(name="pool", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> pool;

    public Output<Optional<String>> pool() {
        return Codegen.optional(this.pool);
    }
    @Export(name="userData", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> userData;

    public Output<Optional<String>> userData() {
        return Codegen.optional(this.userData);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CloudinitDisk(java.lang.String name) {
        this(name, CloudinitDiskArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CloudinitDisk(java.lang.String name, @Nullable CloudinitDiskArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CloudinitDisk(java.lang.String name, @Nullable CloudinitDiskArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/cloudinitDisk:CloudinitDisk", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false, Utilities.getPackageRef());
    }

    private CloudinitDisk(java.lang.String name, Output<java.lang.String> id, @Nullable CloudinitDiskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("libvirt:index/cloudinitDisk:CloudinitDisk", name, state, makeResourceOptions(options, id), false, Utilities.getPackageRef());
    }

    private static CloudinitDiskArgs makeArgs(@Nullable CloudinitDiskArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? CloudinitDiskArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CloudinitDisk get(java.lang.String name, Output<java.lang.String> id, @Nullable CloudinitDiskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CloudinitDisk(name, id, state, options);
    }
}
