// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.libvirt.inputs.NetworkDhcpArgs;
import com.pulumi.libvirt.inputs.NetworkDnsArgs;
import com.pulumi.libvirt.inputs.NetworkDnsmasqOptionsArgs;
import com.pulumi.libvirt.inputs.NetworkRouteArgs;
import com.pulumi.libvirt.inputs.NetworkXmlArgs;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class NetworkArgs extends com.pulumi.resources.ResourceArgs {

    public static final NetworkArgs Empty = new NetworkArgs();

    @Import(name="addresses")
    private @Nullable Output<List<String>> addresses;

    public Optional<Output<List<String>>> addresses() {
        return Optional.ofNullable(this.addresses);
    }

    @Import(name="autostart")
    private @Nullable Output<Boolean> autostart;

    public Optional<Output<Boolean>> autostart() {
        return Optional.ofNullable(this.autostart);
    }

    @Import(name="bridge")
    private @Nullable Output<String> bridge;

    public Optional<Output<String>> bridge() {
        return Optional.ofNullable(this.bridge);
    }

    @Import(name="dhcp")
    private @Nullable Output<NetworkDhcpArgs> dhcp;

    public Optional<Output<NetworkDhcpArgs>> dhcp() {
        return Optional.ofNullable(this.dhcp);
    }

    @Import(name="dns")
    private @Nullable Output<NetworkDnsArgs> dns;

    public Optional<Output<NetworkDnsArgs>> dns() {
        return Optional.ofNullable(this.dns);
    }

    @Import(name="dnsmasqOptions")
    private @Nullable Output<NetworkDnsmasqOptionsArgs> dnsmasqOptions;

    public Optional<Output<NetworkDnsmasqOptionsArgs>> dnsmasqOptions() {
        return Optional.ofNullable(this.dnsmasqOptions);
    }

    @Import(name="domain")
    private @Nullable Output<String> domain;

    public Optional<Output<String>> domain() {
        return Optional.ofNullable(this.domain);
    }

    @Import(name="mode")
    private @Nullable Output<String> mode;

    public Optional<Output<String>> mode() {
        return Optional.ofNullable(this.mode);
    }

    @Import(name="mtu")
    private @Nullable Output<Double> mtu;

    public Optional<Output<Double>> mtu() {
        return Optional.ofNullable(this.mtu);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="networkId")
    private @Nullable Output<String> networkId;

    public Optional<Output<String>> networkId() {
        return Optional.ofNullable(this.networkId);
    }

    @Import(name="routes")
    private @Nullable Output<List<NetworkRouteArgs>> routes;

    public Optional<Output<List<NetworkRouteArgs>>> routes() {
        return Optional.ofNullable(this.routes);
    }

    @Import(name="xml")
    private @Nullable Output<NetworkXmlArgs> xml;

    public Optional<Output<NetworkXmlArgs>> xml() {
        return Optional.ofNullable(this.xml);
    }

    private NetworkArgs() {}

    private NetworkArgs(NetworkArgs $) {
        this.addresses = $.addresses;
        this.autostart = $.autostart;
        this.bridge = $.bridge;
        this.dhcp = $.dhcp;
        this.dns = $.dns;
        this.dnsmasqOptions = $.dnsmasqOptions;
        this.domain = $.domain;
        this.mode = $.mode;
        this.mtu = $.mtu;
        this.name = $.name;
        this.networkId = $.networkId;
        this.routes = $.routes;
        this.xml = $.xml;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(NetworkArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private NetworkArgs $;

        public Builder() {
            $ = new NetworkArgs();
        }

        public Builder(NetworkArgs defaults) {
            $ = new NetworkArgs(Objects.requireNonNull(defaults));
        }

        public Builder addresses(@Nullable Output<List<String>> addresses) {
            $.addresses = addresses;
            return this;
        }

        public Builder addresses(List<String> addresses) {
            return addresses(Output.of(addresses));
        }

        public Builder addresses(String... addresses) {
            return addresses(List.of(addresses));
        }

        public Builder autostart(@Nullable Output<Boolean> autostart) {
            $.autostart = autostart;
            return this;
        }

        public Builder autostart(Boolean autostart) {
            return autostart(Output.of(autostart));
        }

        public Builder bridge(@Nullable Output<String> bridge) {
            $.bridge = bridge;
            return this;
        }

        public Builder bridge(String bridge) {
            return bridge(Output.of(bridge));
        }

        public Builder dhcp(@Nullable Output<NetworkDhcpArgs> dhcp) {
            $.dhcp = dhcp;
            return this;
        }

        public Builder dhcp(NetworkDhcpArgs dhcp) {
            return dhcp(Output.of(dhcp));
        }

        public Builder dns(@Nullable Output<NetworkDnsArgs> dns) {
            $.dns = dns;
            return this;
        }

        public Builder dns(NetworkDnsArgs dns) {
            return dns(Output.of(dns));
        }

        public Builder dnsmasqOptions(@Nullable Output<NetworkDnsmasqOptionsArgs> dnsmasqOptions) {
            $.dnsmasqOptions = dnsmasqOptions;
            return this;
        }

        public Builder dnsmasqOptions(NetworkDnsmasqOptionsArgs dnsmasqOptions) {
            return dnsmasqOptions(Output.of(dnsmasqOptions));
        }

        public Builder domain(@Nullable Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public Builder mode(@Nullable Output<String> mode) {
            $.mode = mode;
            return this;
        }

        public Builder mode(String mode) {
            return mode(Output.of(mode));
        }

        public Builder mtu(@Nullable Output<Double> mtu) {
            $.mtu = mtu;
            return this;
        }

        public Builder mtu(Double mtu) {
            return mtu(Output.of(mtu));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder networkId(@Nullable Output<String> networkId) {
            $.networkId = networkId;
            return this;
        }

        public Builder networkId(String networkId) {
            return networkId(Output.of(networkId));
        }

        public Builder routes(@Nullable Output<List<NetworkRouteArgs>> routes) {
            $.routes = routes;
            return this;
        }

        public Builder routes(List<NetworkRouteArgs> routes) {
            return routes(Output.of(routes));
        }

        public Builder routes(NetworkRouteArgs... routes) {
            return routes(List.of(routes));
        }

        public Builder xml(@Nullable Output<NetworkXmlArgs> xml) {
            $.xml = xml;
            return this;
        }

        public Builder xml(NetworkXmlArgs xml) {
            return xml(Output.of(xml));
        }

        public NetworkArgs build() {
            return $;
        }
    }

}
