// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.libvirt.inputs.VolumeXmlArgs;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class VolumeArgs extends com.pulumi.resources.ResourceArgs {

    public static final VolumeArgs Empty = new VolumeArgs();

    @Import(name="baseVolumeId")
    private @Nullable Output<String> baseVolumeId;

    public Optional<Output<String>> baseVolumeId() {
        return Optional.ofNullable(this.baseVolumeId);
    }

    @Import(name="baseVolumeName")
    private @Nullable Output<String> baseVolumeName;

    public Optional<Output<String>> baseVolumeName() {
        return Optional.ofNullable(this.baseVolumeName);
    }

    @Import(name="baseVolumePool")
    private @Nullable Output<String> baseVolumePool;

    public Optional<Output<String>> baseVolumePool() {
        return Optional.ofNullable(this.baseVolumePool);
    }

    @Import(name="format")
    private @Nullable Output<String> format;

    public Optional<Output<String>> format() {
        return Optional.ofNullable(this.format);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="pool")
    private @Nullable Output<String> pool;

    public Optional<Output<String>> pool() {
        return Optional.ofNullable(this.pool);
    }

    @Import(name="size")
    private @Nullable Output<Double> size;

    public Optional<Output<Double>> size() {
        return Optional.ofNullable(this.size);
    }

    @Import(name="source")
    private @Nullable Output<String> source;

    public Optional<Output<String>> source() {
        return Optional.ofNullable(this.source);
    }

    @Import(name="volumeId")
    private @Nullable Output<String> volumeId;

    public Optional<Output<String>> volumeId() {
        return Optional.ofNullable(this.volumeId);
    }

    @Import(name="xml")
    private @Nullable Output<VolumeXmlArgs> xml;

    public Optional<Output<VolumeXmlArgs>> xml() {
        return Optional.ofNullable(this.xml);
    }

    private VolumeArgs() {}

    private VolumeArgs(VolumeArgs $) {
        this.baseVolumeId = $.baseVolumeId;
        this.baseVolumeName = $.baseVolumeName;
        this.baseVolumePool = $.baseVolumePool;
        this.format = $.format;
        this.name = $.name;
        this.pool = $.pool;
        this.size = $.size;
        this.source = $.source;
        this.volumeId = $.volumeId;
        this.xml = $.xml;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(VolumeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private VolumeArgs $;

        public Builder() {
            $ = new VolumeArgs();
        }

        public Builder(VolumeArgs defaults) {
            $ = new VolumeArgs(Objects.requireNonNull(defaults));
        }

        public Builder baseVolumeId(@Nullable Output<String> baseVolumeId) {
            $.baseVolumeId = baseVolumeId;
            return this;
        }

        public Builder baseVolumeId(String baseVolumeId) {
            return baseVolumeId(Output.of(baseVolumeId));
        }

        public Builder baseVolumeName(@Nullable Output<String> baseVolumeName) {
            $.baseVolumeName = baseVolumeName;
            return this;
        }

        public Builder baseVolumeName(String baseVolumeName) {
            return baseVolumeName(Output.of(baseVolumeName));
        }

        public Builder baseVolumePool(@Nullable Output<String> baseVolumePool) {
            $.baseVolumePool = baseVolumePool;
            return this;
        }

        public Builder baseVolumePool(String baseVolumePool) {
            return baseVolumePool(Output.of(baseVolumePool));
        }

        public Builder format(@Nullable Output<String> format) {
            $.format = format;
            return this;
        }

        public Builder format(String format) {
            return format(Output.of(format));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder pool(@Nullable Output<String> pool) {
            $.pool = pool;
            return this;
        }

        public Builder pool(String pool) {
            return pool(Output.of(pool));
        }

        public Builder size(@Nullable Output<Double> size) {
            $.size = size;
            return this;
        }

        public Builder size(Double size) {
            return size(Output.of(size));
        }

        public Builder source(@Nullable Output<String> source) {
            $.source = source;
            return this;
        }

        public Builder source(String source) {
            return source(Output.of(source));
        }

        public Builder volumeId(@Nullable Output<String> volumeId) {
            $.volumeId = volumeId;
            return this;
        }

        public Builder volumeId(String volumeId) {
            return volumeId(Output.of(volumeId));
        }

        public Builder xml(@Nullable Output<VolumeXmlArgs> xml) {
            $.xml = xml;
            return this;
        }

        public Builder xml(VolumeXmlArgs xml) {
            return xml(Output.of(xml));
        }

        public VolumeArgs build() {
            return $;
        }
    }

}
