// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainTimeoutsArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainTimeoutsArgs Empty = new DomainTimeoutsArgs();

    @Import(name="create")
    private @Nullable Output<String> create;

    public Optional<Output<String>> create() {
        return Optional.ofNullable(this.create);
    }

    private DomainTimeoutsArgs() {}

    private DomainTimeoutsArgs(DomainTimeoutsArgs $) {
        this.create = $.create;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainTimeoutsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainTimeoutsArgs $;

        public Builder() {
            $ = new DomainTimeoutsArgs();
        }

        public Builder(DomainTimeoutsArgs defaults) {
            $ = new DomainTimeoutsArgs(Objects.requireNonNull(defaults));
        }

        public Builder create(@Nullable Output<String> create) {
            $.create = create;
            return this;
        }

        public Builder create(String create) {
            return create(Output.of(create));
        }

        public DomainTimeoutsArgs build() {
            return $;
        }
    }

}
