// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainVideoArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainVideoArgs Empty = new DomainVideoArgs();

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private DomainVideoArgs() {}

    private DomainVideoArgs(DomainVideoArgs $) {
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainVideoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainVideoArgs $;

        public Builder() {
            $ = new DomainVideoArgs();
        }

        public Builder(DomainVideoArgs defaults) {
            $ = new DomainVideoArgs(Objects.requireNonNull(defaults));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public DomainVideoArgs build() {
            return $;
        }
    }

}
