// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.libvirt.inputs.GetNodeDeviceInfoCapabilityIommuGroupArgs;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeDeviceInfoCapabilityArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetNodeDeviceInfoCapabilityArgs Empty = new GetNodeDeviceInfoCapabilityArgs();

    @Import(name="address")
    private @Nullable Output<String> address;

    public Optional<Output<String>> address() {
        return Optional.ofNullable(this.address);
    }

    @Import(name="block", required=true)
    private Output<String> block;

    public Output<String> block() {
        return this.block;
    }

    @Import(name="bus", required=true)
    private Output<String> bus;

    public Output<String> bus() {
        return this.bus;
    }

    @Import(name="capability")
    private @Nullable Output<Map<String,String>> capability;

    public Optional<Output<Map<String,String>>> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="class", required=true)
    private Output<String> class_;

    public Output<String> class_() {
        return this.class_;
    }

    @Import(name="description", required=true)
    private Output<String> description;

    public Output<String> description() {
        return this.description;
    }

    @Import(name="device", required=true)
    private Output<String> device;

    public Output<String> device() {
        return this.device;
    }

    @Import(name="domain", required=true)
    private Output<String> domain;

    public Output<String> domain() {
        return this.domain;
    }

    @Import(name="driveType", required=true)
    private Output<String> driveType;

    public Output<String> driveType() {
        return this.driveType;
    }

    @Import(name="drmType", required=true)
    private Output<String> drmType;

    public Output<String> drmType() {
        return this.drmType;
    }

    @Import(name="features")
    private @Nullable Output<List<String>> features;

    public Optional<Output<List<String>>> features() {
        return Optional.ofNullable(this.features);
    }

    @Import(name="firmware")
    private @Nullable Output<Map<String,String>> firmware;

    public Optional<Output<Map<String,String>>> firmware() {
        return Optional.ofNullable(this.firmware);
    }

    @Import(name="function", required=true)
    private Output<String> function;

    public Output<String> function() {
        return this.function;
    }

    @Import(name="hardware")
    private @Nullable Output<Map<String,String>> hardware;

    public Optional<Output<Map<String,String>>> hardware() {
        return Optional.ofNullable(this.hardware);
    }

    @Import(name="host", required=true)
    private Output<String> host;

    public Output<String> host() {
        return this.host;
    }

    @Import(name="interface")
    private @Nullable Output<String> interface_;

    public Optional<Output<String>> interface_() {
        return Optional.ofNullable(this.interface_);
    }

    @Import(name="iommuGroup")
    private @Nullable Output<GetNodeDeviceInfoCapabilityIommuGroupArgs> iommuGroup;

    public Optional<Output<GetNodeDeviceInfoCapabilityIommuGroupArgs>> iommuGroup() {
        return Optional.ofNullable(this.iommuGroup);
    }

    @Import(name="link")
    private @Nullable Output<Map<String,String>> link;

    public Optional<Output<Map<String,String>>> link() {
        return Optional.ofNullable(this.link);
    }

    @Import(name="logicalBlockSize", required=true)
    private Output<String> logicalBlockSize;

    public Output<String> logicalBlockSize() {
        return this.logicalBlockSize;
    }

    @Import(name="lun", required=true)
    private Output<String> lun;

    public Output<String> lun() {
        return this.lun;
    }

    @Import(name="model", required=true)
    private Output<String> model;

    public Output<String> model() {
        return this.model;
    }

    @Import(name="numBlocks", required=true)
    private Output<String> numBlocks;

    public Output<String> numBlocks() {
        return this.numBlocks;
    }

    @Import(name="number", required=true)
    private Output<String> number;

    public Output<String> number() {
        return this.number;
    }

    @Import(name="product")
    private @Nullable Output<Map<String,String>> product;

    public Optional<Output<Map<String,String>>> product() {
        return Optional.ofNullable(this.product);
    }

    @Import(name="protocol", required=true)
    private Output<String> protocol;

    public Output<String> protocol() {
        return this.protocol;
    }

    @Import(name="scsiType", required=true)
    private Output<String> scsiType;

    public Output<String> scsiType() {
        return this.scsiType;
    }

    @Import(name="serial", required=true)
    private Output<String> serial;

    public Output<String> serial() {
        return this.serial;
    }

    @Import(name="size", required=true)
    private Output<String> size;

    public Output<String> size() {
        return this.size;
    }

    @Import(name="slot", required=true)
    private Output<String> slot;

    public Output<String> slot() {
        return this.slot;
    }

    @Import(name="subclass", required=true)
    private Output<String> subclass;

    public Output<String> subclass() {
        return this.subclass;
    }

    @Import(name="target", required=true)
    private Output<String> target;

    public Output<String> target() {
        return this.target;
    }

    @Import(name="type", required=true)
    private Output<String> type;

    public Output<String> type() {
        return this.type;
    }

    @Import(name="uniqueId", required=true)
    private Output<String> uniqueId;

    public Output<String> uniqueId() {
        return this.uniqueId;
    }

    @Import(name="vendor")
    private @Nullable Output<Map<String,String>> vendor;

    public Optional<Output<Map<String,String>>> vendor() {
        return Optional.ofNullable(this.vendor);
    }

    private GetNodeDeviceInfoCapabilityArgs() {}

    private GetNodeDeviceInfoCapabilityArgs(GetNodeDeviceInfoCapabilityArgs $) {
        this.address = $.address;
        this.block = $.block;
        this.bus = $.bus;
        this.capability = $.capability;
        this.class_ = $.class_;
        this.description = $.description;
        this.device = $.device;
        this.domain = $.domain;
        this.driveType = $.driveType;
        this.drmType = $.drmType;
        this.features = $.features;
        this.firmware = $.firmware;
        this.function = $.function;
        this.hardware = $.hardware;
        this.host = $.host;
        this.interface_ = $.interface_;
        this.iommuGroup = $.iommuGroup;
        this.link = $.link;
        this.logicalBlockSize = $.logicalBlockSize;
        this.lun = $.lun;
        this.model = $.model;
        this.numBlocks = $.numBlocks;
        this.number = $.number;
        this.product = $.product;
        this.protocol = $.protocol;
        this.scsiType = $.scsiType;
        this.serial = $.serial;
        this.size = $.size;
        this.slot = $.slot;
        this.subclass = $.subclass;
        this.target = $.target;
        this.type = $.type;
        this.uniqueId = $.uniqueId;
        this.vendor = $.vendor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDeviceInfoCapabilityArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDeviceInfoCapabilityArgs $;

        public Builder() {
            $ = new GetNodeDeviceInfoCapabilityArgs();
        }

        public Builder(GetNodeDeviceInfoCapabilityArgs defaults) {
            $ = new GetNodeDeviceInfoCapabilityArgs(Objects.requireNonNull(defaults));
        }

        public Builder address(@Nullable Output<String> address) {
            $.address = address;
            return this;
        }

        public Builder address(String address) {
            return address(Output.of(address));
        }

        public Builder block(Output<String> block) {
            $.block = block;
            return this;
        }

        public Builder block(String block) {
            return block(Output.of(block));
        }

        public Builder bus(Output<String> bus) {
            $.bus = bus;
            return this;
        }

        public Builder bus(String bus) {
            return bus(Output.of(bus));
        }

        public Builder capability(@Nullable Output<Map<String,String>> capability) {
            $.capability = capability;
            return this;
        }

        public Builder capability(Map<String,String> capability) {
            return capability(Output.of(capability));
        }

        public Builder class_(Output<String> class_) {
            $.class_ = class_;
            return this;
        }

        public Builder class_(String class_) {
            return class_(Output.of(class_));
        }

        public Builder description(Output<String> description) {
            $.description = description;
            return this;
        }

        public Builder description(String description) {
            return description(Output.of(description));
        }

        public Builder device(Output<String> device) {
            $.device = device;
            return this;
        }

        public Builder device(String device) {
            return device(Output.of(device));
        }

        public Builder domain(Output<String> domain) {
            $.domain = domain;
            return this;
        }

        public Builder domain(String domain) {
            return domain(Output.of(domain));
        }

        public Builder driveType(Output<String> driveType) {
            $.driveType = driveType;
            return this;
        }

        public Builder driveType(String driveType) {
            return driveType(Output.of(driveType));
        }

        public Builder drmType(Output<String> drmType) {
            $.drmType = drmType;
            return this;
        }

        public Builder drmType(String drmType) {
            return drmType(Output.of(drmType));
        }

        public Builder features(@Nullable Output<List<String>> features) {
            $.features = features;
            return this;
        }

        public Builder features(List<String> features) {
            return features(Output.of(features));
        }

        public Builder features(String... features) {
            return features(List.of(features));
        }

        public Builder firmware(@Nullable Output<Map<String,String>> firmware) {
            $.firmware = firmware;
            return this;
        }

        public Builder firmware(Map<String,String> firmware) {
            return firmware(Output.of(firmware));
        }

        public Builder function(Output<String> function) {
            $.function = function;
            return this;
        }

        public Builder function(String function) {
            return function(Output.of(function));
        }

        public Builder hardware(@Nullable Output<Map<String,String>> hardware) {
            $.hardware = hardware;
            return this;
        }

        public Builder hardware(Map<String,String> hardware) {
            return hardware(Output.of(hardware));
        }

        public Builder host(Output<String> host) {
            $.host = host;
            return this;
        }

        public Builder host(String host) {
            return host(Output.of(host));
        }

        public Builder interface_(@Nullable Output<String> interface_) {
            $.interface_ = interface_;
            return this;
        }

        public Builder interface_(String interface_) {
            return interface_(Output.of(interface_));
        }

        public Builder iommuGroup(@Nullable Output<GetNodeDeviceInfoCapabilityIommuGroupArgs> iommuGroup) {
            $.iommuGroup = iommuGroup;
            return this;
        }

        public Builder iommuGroup(GetNodeDeviceInfoCapabilityIommuGroupArgs iommuGroup) {
            return iommuGroup(Output.of(iommuGroup));
        }

        public Builder link(@Nullable Output<Map<String,String>> link) {
            $.link = link;
            return this;
        }

        public Builder link(Map<String,String> link) {
            return link(Output.of(link));
        }

        public Builder logicalBlockSize(Output<String> logicalBlockSize) {
            $.logicalBlockSize = logicalBlockSize;
            return this;
        }

        public Builder logicalBlockSize(String logicalBlockSize) {
            return logicalBlockSize(Output.of(logicalBlockSize));
        }

        public Builder lun(Output<String> lun) {
            $.lun = lun;
            return this;
        }

        public Builder lun(String lun) {
            return lun(Output.of(lun));
        }

        public Builder model(Output<String> model) {
            $.model = model;
            return this;
        }

        public Builder model(String model) {
            return model(Output.of(model));
        }

        public Builder numBlocks(Output<String> numBlocks) {
            $.numBlocks = numBlocks;
            return this;
        }

        public Builder numBlocks(String numBlocks) {
            return numBlocks(Output.of(numBlocks));
        }

        public Builder number(Output<String> number) {
            $.number = number;
            return this;
        }

        public Builder number(String number) {
            return number(Output.of(number));
        }

        public Builder product(@Nullable Output<Map<String,String>> product) {
            $.product = product;
            return this;
        }

        public Builder product(Map<String,String> product) {
            return product(Output.of(product));
        }

        public Builder protocol(Output<String> protocol) {
            $.protocol = protocol;
            return this;
        }

        public Builder protocol(String protocol) {
            return protocol(Output.of(protocol));
        }

        public Builder scsiType(Output<String> scsiType) {
            $.scsiType = scsiType;
            return this;
        }

        public Builder scsiType(String scsiType) {
            return scsiType(Output.of(scsiType));
        }

        public Builder serial(Output<String> serial) {
            $.serial = serial;
            return this;
        }

        public Builder serial(String serial) {
            return serial(Output.of(serial));
        }

        public Builder size(Output<String> size) {
            $.size = size;
            return this;
        }

        public Builder size(String size) {
            return size(Output.of(size));
        }

        public Builder slot(Output<String> slot) {
            $.slot = slot;
            return this;
        }

        public Builder slot(String slot) {
            return slot(Output.of(slot));
        }

        public Builder subclass(Output<String> subclass) {
            $.subclass = subclass;
            return this;
        }

        public Builder subclass(String subclass) {
            return subclass(Output.of(subclass));
        }

        public Builder target(Output<String> target) {
            $.target = target;
            return this;
        }

        public Builder target(String target) {
            return target(Output.of(target));
        }

        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public Builder uniqueId(Output<String> uniqueId) {
            $.uniqueId = uniqueId;
            return this;
        }

        public Builder uniqueId(String uniqueId) {
            return uniqueId(Output.of(uniqueId));
        }

        public Builder vendor(@Nullable Output<Map<String,String>> vendor) {
            $.vendor = vendor;
            return this;
        }

        public Builder vendor(Map<String,String> vendor) {
            return vendor(Output.of(vendor));
        }

        public GetNodeDeviceInfoCapabilityArgs build() {
            if ($.block == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "block");
            }
            if ($.bus == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "bus");
            }
            if ($.class_ == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "class_");
            }
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "description");
            }
            if ($.device == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "device");
            }
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "domain");
            }
            if ($.driveType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "driveType");
            }
            if ($.drmType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "drmType");
            }
            if ($.function == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "function");
            }
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "host");
            }
            if ($.logicalBlockSize == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "logicalBlockSize");
            }
            if ($.lun == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "lun");
            }
            if ($.model == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "model");
            }
            if ($.numBlocks == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "numBlocks");
            }
            if ($.number == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "number");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "protocol");
            }
            if ($.scsiType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "scsiType");
            }
            if ($.serial == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "serial");
            }
            if ($.size == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "size");
            }
            if ($.slot == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "slot");
            }
            if ($.subclass == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "subclass");
            }
            if ($.target == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "target");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "type");
            }
            if ($.uniqueId == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapabilityArgs", "uniqueId");
            }
            return $;
        }
    }

}
