// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.libvirt.inputs.GetNodeDeviceInfoCapabilityIommuGroup;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeDeviceInfoCapability extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeDeviceInfoCapability Empty = new GetNodeDeviceInfoCapability();

    @Import(name="address")
    private @Nullable String address;

    public Optional<String> address() {
        return Optional.ofNullable(this.address);
    }

    @Import(name="block", required=true)
    private String block;

    public String block() {
        return this.block;
    }

    @Import(name="bus", required=true)
    private String bus;

    public String bus() {
        return this.bus;
    }

    @Import(name="capability")
    private @Nullable Map<String,String> capability;

    public Optional<Map<String,String>> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="class", required=true)
    private String class_;

    public String class_() {
        return this.class_;
    }

    @Import(name="description", required=true)
    private String description;

    public String description() {
        return this.description;
    }

    @Import(name="device", required=true)
    private String device;

    public String device() {
        return this.device;
    }

    @Import(name="domain", required=true)
    private String domain;

    public String domain() {
        return this.domain;
    }

    @Import(name="driveType", required=true)
    private String driveType;

    public String driveType() {
        return this.driveType;
    }

    @Import(name="drmType", required=true)
    private String drmType;

    public String drmType() {
        return this.drmType;
    }

    @Import(name="features")
    private @Nullable List<String> features;

    public Optional<List<String>> features() {
        return Optional.ofNullable(this.features);
    }

    @Import(name="firmware")
    private @Nullable Map<String,String> firmware;

    public Optional<Map<String,String>> firmware() {
        return Optional.ofNullable(this.firmware);
    }

    @Import(name="function", required=true)
    private String function;

    public String function() {
        return this.function;
    }

    @Import(name="hardware")
    private @Nullable Map<String,String> hardware;

    public Optional<Map<String,String>> hardware() {
        return Optional.ofNullable(this.hardware);
    }

    @Import(name="host", required=true)
    private String host;

    public String host() {
        return this.host;
    }

    @Import(name="interface")
    private @Nullable String interface_;

    public Optional<String> interface_() {
        return Optional.ofNullable(this.interface_);
    }

    @Import(name="iommuGroup")
    private @Nullable GetNodeDeviceInfoCapabilityIommuGroup iommuGroup;

    public Optional<GetNodeDeviceInfoCapabilityIommuGroup> iommuGroup() {
        return Optional.ofNullable(this.iommuGroup);
    }

    @Import(name="link")
    private @Nullable Map<String,String> link;

    public Optional<Map<String,String>> link() {
        return Optional.ofNullable(this.link);
    }

    @Import(name="logicalBlockSize", required=true)
    private String logicalBlockSize;

    public String logicalBlockSize() {
        return this.logicalBlockSize;
    }

    @Import(name="lun", required=true)
    private String lun;

    public String lun() {
        return this.lun;
    }

    @Import(name="model", required=true)
    private String model;

    public String model() {
        return this.model;
    }

    @Import(name="numBlocks", required=true)
    private String numBlocks;

    public String numBlocks() {
        return this.numBlocks;
    }

    @Import(name="number", required=true)
    private String number;

    public String number() {
        return this.number;
    }

    @Import(name="product")
    private @Nullable Map<String,String> product;

    public Optional<Map<String,String>> product() {
        return Optional.ofNullable(this.product);
    }

    @Import(name="protocol", required=true)
    private String protocol;

    public String protocol() {
        return this.protocol;
    }

    @Import(name="scsiType", required=true)
    private String scsiType;

    public String scsiType() {
        return this.scsiType;
    }

    @Import(name="serial", required=true)
    private String serial;

    public String serial() {
        return this.serial;
    }

    @Import(name="size", required=true)
    private String size;

    public String size() {
        return this.size;
    }

    @Import(name="slot", required=true)
    private String slot;

    public String slot() {
        return this.slot;
    }

    @Import(name="subclass", required=true)
    private String subclass;

    public String subclass() {
        return this.subclass;
    }

    @Import(name="target", required=true)
    private String target;

    public String target() {
        return this.target;
    }

    @Import(name="type", required=true)
    private String type;

    public String type() {
        return this.type;
    }

    @Import(name="uniqueId", required=true)
    private String uniqueId;

    public String uniqueId() {
        return this.uniqueId;
    }

    @Import(name="vendor")
    private @Nullable Map<String,String> vendor;

    public Optional<Map<String,String>> vendor() {
        return Optional.ofNullable(this.vendor);
    }

    private GetNodeDeviceInfoCapability() {}

    private GetNodeDeviceInfoCapability(GetNodeDeviceInfoCapability $) {
        this.address = $.address;
        this.block = $.block;
        this.bus = $.bus;
        this.capability = $.capability;
        this.class_ = $.class_;
        this.description = $.description;
        this.device = $.device;
        this.domain = $.domain;
        this.driveType = $.driveType;
        this.drmType = $.drmType;
        this.features = $.features;
        this.firmware = $.firmware;
        this.function = $.function;
        this.hardware = $.hardware;
        this.host = $.host;
        this.interface_ = $.interface_;
        this.iommuGroup = $.iommuGroup;
        this.link = $.link;
        this.logicalBlockSize = $.logicalBlockSize;
        this.lun = $.lun;
        this.model = $.model;
        this.numBlocks = $.numBlocks;
        this.number = $.number;
        this.product = $.product;
        this.protocol = $.protocol;
        this.scsiType = $.scsiType;
        this.serial = $.serial;
        this.size = $.size;
        this.slot = $.slot;
        this.subclass = $.subclass;
        this.target = $.target;
        this.type = $.type;
        this.uniqueId = $.uniqueId;
        this.vendor = $.vendor;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDeviceInfoCapability defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDeviceInfoCapability $;

        public Builder() {
            $ = new GetNodeDeviceInfoCapability();
        }

        public Builder(GetNodeDeviceInfoCapability defaults) {
            $ = new GetNodeDeviceInfoCapability(Objects.requireNonNull(defaults));
        }

        public Builder address(@Nullable String address) {
            $.address = address;
            return this;
        }

        public Builder block(String block) {
            $.block = block;
            return this;
        }

        public Builder bus(String bus) {
            $.bus = bus;
            return this;
        }

        public Builder capability(@Nullable Map<String,String> capability) {
            $.capability = capability;
            return this;
        }

        public Builder class_(String class_) {
            $.class_ = class_;
            return this;
        }

        public Builder description(String description) {
            $.description = description;
            return this;
        }

        public Builder device(String device) {
            $.device = device;
            return this;
        }

        public Builder domain(String domain) {
            $.domain = domain;
            return this;
        }

        public Builder driveType(String driveType) {
            $.driveType = driveType;
            return this;
        }

        public Builder drmType(String drmType) {
            $.drmType = drmType;
            return this;
        }

        public Builder features(@Nullable List<String> features) {
            $.features = features;
            return this;
        }

        public Builder features(String... features) {
            return features(List.of(features));
        }

        public Builder firmware(@Nullable Map<String,String> firmware) {
            $.firmware = firmware;
            return this;
        }

        public Builder function(String function) {
            $.function = function;
            return this;
        }

        public Builder hardware(@Nullable Map<String,String> hardware) {
            $.hardware = hardware;
            return this;
        }

        public Builder host(String host) {
            $.host = host;
            return this;
        }

        public Builder interface_(@Nullable String interface_) {
            $.interface_ = interface_;
            return this;
        }

        public Builder iommuGroup(@Nullable GetNodeDeviceInfoCapabilityIommuGroup iommuGroup) {
            $.iommuGroup = iommuGroup;
            return this;
        }

        public Builder link(@Nullable Map<String,String> link) {
            $.link = link;
            return this;
        }

        public Builder logicalBlockSize(String logicalBlockSize) {
            $.logicalBlockSize = logicalBlockSize;
            return this;
        }

        public Builder lun(String lun) {
            $.lun = lun;
            return this;
        }

        public Builder model(String model) {
            $.model = model;
            return this;
        }

        public Builder numBlocks(String numBlocks) {
            $.numBlocks = numBlocks;
            return this;
        }

        public Builder number(String number) {
            $.number = number;
            return this;
        }

        public Builder product(@Nullable Map<String,String> product) {
            $.product = product;
            return this;
        }

        public Builder protocol(String protocol) {
            $.protocol = protocol;
            return this;
        }

        public Builder scsiType(String scsiType) {
            $.scsiType = scsiType;
            return this;
        }

        public Builder serial(String serial) {
            $.serial = serial;
            return this;
        }

        public Builder size(String size) {
            $.size = size;
            return this;
        }

        public Builder slot(String slot) {
            $.slot = slot;
            return this;
        }

        public Builder subclass(String subclass) {
            $.subclass = subclass;
            return this;
        }

        public Builder target(String target) {
            $.target = target;
            return this;
        }

        public Builder type(String type) {
            $.type = type;
            return this;
        }

        public Builder uniqueId(String uniqueId) {
            $.uniqueId = uniqueId;
            return this;
        }

        public Builder vendor(@Nullable Map<String,String> vendor) {
            $.vendor = vendor;
            return this;
        }

        public GetNodeDeviceInfoCapability build() {
            if ($.block == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "block");
            }
            if ($.bus == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "bus");
            }
            if ($.class_ == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "class_");
            }
            if ($.description == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "description");
            }
            if ($.device == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "device");
            }
            if ($.domain == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "domain");
            }
            if ($.driveType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "driveType");
            }
            if ($.drmType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "drmType");
            }
            if ($.function == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "function");
            }
            if ($.host == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "host");
            }
            if ($.logicalBlockSize == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "logicalBlockSize");
            }
            if ($.lun == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "lun");
            }
            if ($.model == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "model");
            }
            if ($.numBlocks == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "numBlocks");
            }
            if ($.number == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "number");
            }
            if ($.protocol == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "protocol");
            }
            if ($.scsiType == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "scsiType");
            }
            if ($.serial == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "serial");
            }
            if ($.size == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "size");
            }
            if ($.slot == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "slot");
            }
            if ($.subclass == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "subclass");
            }
            if ($.target == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "target");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "type");
            }
            if ($.uniqueId == null) {
                throw new MissingRequiredPropertyException("GetNodeDeviceInfoCapability", "uniqueId");
            }
            return $;
        }
    }

}
