// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeInfoArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeInfoArgs Empty = new GetNodeInfoArgs();

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    private GetNodeInfoArgs() {}

    private GetNodeInfoArgs(GetNodeInfoArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeInfoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeInfoArgs $;

        public Builder() {
            $ = new GetNodeInfoArgs();
        }

        public Builder(GetNodeInfoArgs defaults) {
            $ = new GetNodeInfoArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetNodeInfoArgs build() {
            return $;
        }
    }

}
