// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeDevicesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeDevicesArgs Empty = new GetNodeDevicesArgs();

    @Import(name="capability")
    private @Nullable Output<String> capability;

    public Optional<Output<String>> capability() {
        return Optional.ofNullable(this.capability);
    }

    @Import(name="id")
    private @Nullable Output<String> id;

    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    private GetNodeDevicesArgs() {}

    private GetNodeDevicesArgs(GetNodeDevicesArgs $) {
        this.capability = $.capability;
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeDevicesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeDevicesArgs $;

        public Builder() {
            $ = new GetNodeDevicesArgs();
        }

        public Builder(GetNodeDevicesArgs defaults) {
            $ = new GetNodeDevicesArgs(Objects.requireNonNull(defaults));
        }

        public Builder capability(@Nullable Output<String> capability) {
            $.capability = capability;
            return this;
        }

        public Builder capability(String capability) {
            return capability(Output.of(capability));
        }

        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        public Builder id(String id) {
            return id(Output.of(id));
        }

        public GetNodeDevicesArgs build() {
            return $;
        }
    }

}
