// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetNodeInfoPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetNodeInfoPlainArgs Empty = new GetNodeInfoPlainArgs();

    @Import(name="id")
    private @Nullable String id;

    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    private GetNodeInfoPlainArgs() {}

    private GetNodeInfoPlainArgs(GetNodeInfoPlainArgs $) {
        this.id = $.id;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetNodeInfoPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetNodeInfoPlainArgs $;

        public Builder() {
            $ = new GetNodeInfoPlainArgs();
        }

        public Builder(GetNodeInfoPlainArgs defaults) {
            $ = new GetNodeInfoPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        public GetNodeInfoPlainArgs build() {
            return $;
        }
    }

}
