// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.libvirt.inputs.PoolSourceArgs;
import com.pulumi.libvirt.inputs.PoolTargetArgs;
import com.pulumi.libvirt.inputs.PoolXmlArgs;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PoolState extends com.pulumi.resources.ResourceArgs {

    public static final PoolState Empty = new PoolState();

    @Import(name="allocation")
    private @Nullable Output<Double> allocation;

    public Optional<Output<Double>> allocation() {
        return Optional.ofNullable(this.allocation);
    }

    @Import(name="available")
    private @Nullable Output<Double> available;

    public Optional<Output<Double>> available() {
        return Optional.ofNullable(this.available);
    }

    @Import(name="capacity")
    private @Nullable Output<Double> capacity;

    public Optional<Output<Double>> capacity() {
        return Optional.ofNullable(this.capacity);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * @deprecated
     * Deprecated
     * 
     */
    @Deprecated /* Deprecated */
    @Import(name="path")
    private @Nullable Output<String> path;

    /**
     * @deprecated
     * Deprecated
     * 
     */
    @Deprecated /* Deprecated */
    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    @Import(name="poolId")
    private @Nullable Output<String> poolId;

    public Optional<Output<String>> poolId() {
        return Optional.ofNullable(this.poolId);
    }

    @Import(name="source")
    private @Nullable Output<PoolSourceArgs> source;

    public Optional<Output<PoolSourceArgs>> source() {
        return Optional.ofNullable(this.source);
    }

    @Import(name="target")
    private @Nullable Output<PoolTargetArgs> target;

    public Optional<Output<PoolTargetArgs>> target() {
        return Optional.ofNullable(this.target);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    @Import(name="xml")
    private @Nullable Output<PoolXmlArgs> xml;

    public Optional<Output<PoolXmlArgs>> xml() {
        return Optional.ofNullable(this.xml);
    }

    private PoolState() {}

    private PoolState(PoolState $) {
        this.allocation = $.allocation;
        this.available = $.available;
        this.capacity = $.capacity;
        this.name = $.name;
        this.path = $.path;
        this.poolId = $.poolId;
        this.source = $.source;
        this.target = $.target;
        this.type = $.type;
        this.xml = $.xml;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PoolState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PoolState $;

        public Builder() {
            $ = new PoolState();
        }

        public Builder(PoolState defaults) {
            $ = new PoolState(Objects.requireNonNull(defaults));
        }

        public Builder allocation(@Nullable Output<Double> allocation) {
            $.allocation = allocation;
            return this;
        }

        public Builder allocation(Double allocation) {
            return allocation(Output.of(allocation));
        }

        public Builder available(@Nullable Output<Double> available) {
            $.available = available;
            return this;
        }

        public Builder available(Double available) {
            return available(Output.of(available));
        }

        public Builder capacity(@Nullable Output<Double> capacity) {
            $.capacity = capacity;
            return this;
        }

        public Builder capacity(Double capacity) {
            return capacity(Output.of(capacity));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @return builder
         * 
         * @deprecated
         * Deprecated
         * 
         */
        @Deprecated /* Deprecated */
        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        /**
         * @return builder
         * 
         * @deprecated
         * Deprecated
         * 
         */
        @Deprecated /* Deprecated */
        public Builder path(String path) {
            return path(Output.of(path));
        }

        public Builder poolId(@Nullable Output<String> poolId) {
            $.poolId = poolId;
            return this;
        }

        public Builder poolId(String poolId) {
            return poolId(Output.of(poolId));
        }

        public Builder source(@Nullable Output<PoolSourceArgs> source) {
            $.source = source;
            return this;
        }

        public Builder source(PoolSourceArgs source) {
            return source(Output.of(source));
        }

        public Builder target(@Nullable Output<PoolTargetArgs> target) {
            $.target = target;
            return this;
        }

        public Builder target(PoolTargetArgs target) {
            return target(Output.of(target));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public Builder xml(@Nullable Output<PoolXmlArgs> xml) {
            $.xml = xml;
            return this;
        }

        public Builder xml(PoolXmlArgs xml) {
            return xml(Output.of(xml));
        }

        public PoolState build() {
            return $;
        }
    }

}
