// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class DomainTpm {
    private @Nullable String backendDevicePath;
    private @Nullable String backendEncryptionSecret;
    private @Nullable Boolean backendPersistentState;
    private @Nullable String backendType;
    private @Nullable String backendVersion;
    private @Nullable String model;

    private DomainTpm() {}
    public Optional<String> backendDevicePath() {
        return Optional.ofNullable(this.backendDevicePath);
    }
    public Optional<String> backendEncryptionSecret() {
        return Optional.ofNullable(this.backendEncryptionSecret);
    }
    public Optional<Boolean> backendPersistentState() {
        return Optional.ofNullable(this.backendPersistentState);
    }
    public Optional<String> backendType() {
        return Optional.ofNullable(this.backendType);
    }
    public Optional<String> backendVersion() {
        return Optional.ofNullable(this.backendVersion);
    }
    public Optional<String> model() {
        return Optional.ofNullable(this.model);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(DomainTpm defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String backendDevicePath;
        private @Nullable String backendEncryptionSecret;
        private @Nullable Boolean backendPersistentState;
        private @Nullable String backendType;
        private @Nullable String backendVersion;
        private @Nullable String model;
        public Builder() {}
        public Builder(DomainTpm defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.backendDevicePath = defaults.backendDevicePath;
    	      this.backendEncryptionSecret = defaults.backendEncryptionSecret;
    	      this.backendPersistentState = defaults.backendPersistentState;
    	      this.backendType = defaults.backendType;
    	      this.backendVersion = defaults.backendVersion;
    	      this.model = defaults.model;
        }

        @CustomType.Setter
        public Builder backendDevicePath(@Nullable String backendDevicePath) {

            this.backendDevicePath = backendDevicePath;
            return this;
        }
        @CustomType.Setter
        public Builder backendEncryptionSecret(@Nullable String backendEncryptionSecret) {

            this.backendEncryptionSecret = backendEncryptionSecret;
            return this;
        }
        @CustomType.Setter
        public Builder backendPersistentState(@Nullable Boolean backendPersistentState) {

            this.backendPersistentState = backendPersistentState;
            return this;
        }
        @CustomType.Setter
        public Builder backendType(@Nullable String backendType) {

            this.backendType = backendType;
            return this;
        }
        @CustomType.Setter
        public Builder backendVersion(@Nullable String backendVersion) {

            this.backendVersion = backendVersion;
            return this;
        }
        @CustomType.Setter
        public Builder model(@Nullable String model) {

            this.model = model;
            return this;
        }
        public DomainTpm build() {
            final var _resultValue = new DomainTpm();
            _resultValue.backendDevicePath = backendDevicePath;
            _resultValue.backendEncryptionSecret = backendEncryptionSecret;
            _resultValue.backendPersistentState = backendPersistentState;
            _resultValue.backendType = backendType;
            _resultValue.backendVersion = backendVersion;
            _resultValue.model = model;
            return _resultValue;
        }
    }
}
