// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetNodeDeviceInfoResult {
    private @Nullable GetNodeDeviceInfoCapability capability;
    private List<GetNodeDeviceInfoDevnode> devnodes;
    private String id;
    private String name;
    private String parent;
    private String path;
    private String xml;

    private GetNodeDeviceInfoResult() {}
    public Optional<GetNodeDeviceInfoCapability> capability() {
        return Optional.ofNullable(this.capability);
    }
    public List<GetNodeDeviceInfoDevnode> devnodes() {
        return this.devnodes;
    }
    public String id() {
        return this.id;
    }
    public String name() {
        return this.name;
    }
    public String parent() {
        return this.parent;
    }
    public String path() {
        return this.path;
    }
    public String xml() {
        return this.xml;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodeDeviceInfoResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetNodeDeviceInfoCapability capability;
        private List<GetNodeDeviceInfoDevnode> devnodes;
        private String id;
        private String name;
        private String parent;
        private String path;
        private String xml;
        public Builder() {}
        public Builder(GetNodeDeviceInfoResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.capability = defaults.capability;
    	      this.devnodes = defaults.devnodes;
    	      this.id = defaults.id;
    	      this.name = defaults.name;
    	      this.parent = defaults.parent;
    	      this.path = defaults.path;
    	      this.xml = defaults.xml;
        }

        @CustomType.Setter
        public Builder capability(@Nullable GetNodeDeviceInfoCapability capability) {

            this.capability = capability;
            return this;
        }
        @CustomType.Setter
        public Builder devnodes(List<GetNodeDeviceInfoDevnode> devnodes) {
            if (devnodes == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "devnodes");
            }
            this.devnodes = devnodes;
            return this;
        }
        public Builder devnodes(GetNodeDeviceInfoDevnode... devnodes) {
            return devnodes(List.of(devnodes));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder parent(String parent) {
            if (parent == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "parent");
            }
            this.parent = parent;
            return this;
        }
        @CustomType.Setter
        public Builder path(String path) {
            if (path == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "path");
            }
            this.path = path;
            return this;
        }
        @CustomType.Setter
        public Builder xml(String xml) {
            if (xml == null) {
              throw new MissingRequiredPropertyException("GetNodeDeviceInfoResult", "xml");
            }
            this.xml = xml;
            return this;
        }
        public GetNodeDeviceInfoResult build() {
            final var _resultValue = new GetNodeDeviceInfoResult();
            _resultValue.capability = capability;
            _resultValue.devnodes = devnodes;
            _resultValue.id = id;
            _resultValue.name = name;
            _resultValue.parent = parent;
            _resultValue.path = path;
            _resultValue.xml = xml;
            return _resultValue;
        }
    }
}
