// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.libvirt.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Double;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNodeInfoResult {
    private Double cpuCoresPerSocket;
    private Double cpuCoresTotal;
    private String cpuModel;
    private Double cpuSockets;
    private Double cpuThreadsPerCore;
    private String id;
    private Double memoryTotalKb;
    private Double numaNodes;

    private GetNodeInfoResult() {}
    public Double cpuCoresPerSocket() {
        return this.cpuCoresPerSocket;
    }
    public Double cpuCoresTotal() {
        return this.cpuCoresTotal;
    }
    public String cpuModel() {
        return this.cpuModel;
    }
    public Double cpuSockets() {
        return this.cpuSockets;
    }
    public Double cpuThreadsPerCore() {
        return this.cpuThreadsPerCore;
    }
    public String id() {
        return this.id;
    }
    public Double memoryTotalKb() {
        return this.memoryTotalKb;
    }
    public Double numaNodes() {
        return this.numaNodes;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodeInfoResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Double cpuCoresPerSocket;
        private Double cpuCoresTotal;
        private String cpuModel;
        private Double cpuSockets;
        private Double cpuThreadsPerCore;
        private String id;
        private Double memoryTotalKb;
        private Double numaNodes;
        public Builder() {}
        public Builder(GetNodeInfoResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cpuCoresPerSocket = defaults.cpuCoresPerSocket;
    	      this.cpuCoresTotal = defaults.cpuCoresTotal;
    	      this.cpuModel = defaults.cpuModel;
    	      this.cpuSockets = defaults.cpuSockets;
    	      this.cpuThreadsPerCore = defaults.cpuThreadsPerCore;
    	      this.id = defaults.id;
    	      this.memoryTotalKb = defaults.memoryTotalKb;
    	      this.numaNodes = defaults.numaNodes;
        }

        @CustomType.Setter
        public Builder cpuCoresPerSocket(Double cpuCoresPerSocket) {
            if (cpuCoresPerSocket == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "cpuCoresPerSocket");
            }
            this.cpuCoresPerSocket = cpuCoresPerSocket;
            return this;
        }
        @CustomType.Setter
        public Builder cpuCoresTotal(Double cpuCoresTotal) {
            if (cpuCoresTotal == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "cpuCoresTotal");
            }
            this.cpuCoresTotal = cpuCoresTotal;
            return this;
        }
        @CustomType.Setter
        public Builder cpuModel(String cpuModel) {
            if (cpuModel == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "cpuModel");
            }
            this.cpuModel = cpuModel;
            return this;
        }
        @CustomType.Setter
        public Builder cpuSockets(Double cpuSockets) {
            if (cpuSockets == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "cpuSockets");
            }
            this.cpuSockets = cpuSockets;
            return this;
        }
        @CustomType.Setter
        public Builder cpuThreadsPerCore(Double cpuThreadsPerCore) {
            if (cpuThreadsPerCore == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "cpuThreadsPerCore");
            }
            this.cpuThreadsPerCore = cpuThreadsPerCore;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder memoryTotalKb(Double memoryTotalKb) {
            if (memoryTotalKb == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "memoryTotalKb");
            }
            this.memoryTotalKb = memoryTotalKb;
            return this;
        }
        @CustomType.Setter
        public Builder numaNodes(Double numaNodes) {
            if (numaNodes == null) {
              throw new MissingRequiredPropertyException("GetNodeInfoResult", "numaNodes");
            }
            this.numaNodes = numaNodes;
            return this;
        }
        public GetNodeInfoResult build() {
            final var _resultValue = new GetNodeInfoResult();
            _resultValue.cpuCoresPerSocket = cpuCoresPerSocket;
            _resultValue.cpuCoresTotal = cpuCoresTotal;
            _resultValue.cpuModel = cpuModel;
            _resultValue.cpuSockets = cpuSockets;
            _resultValue.cpuThreadsPerCore = cpuThreadsPerCore;
            _resultValue.id = id;
            _resultValue.memoryTotalKb = memoryTotalKb;
            _resultValue.numaNodes = numaNodes;
            return _resultValue;
        }
    }
}
